# Onderwerp

## Definities en afkortingen

**31xx**: afkorting voor Natura2000-habitattypen 3110, 3130, 3140, 3150 en 3160

**Habitattypen** van stilstaand water die beschermd zijn door de habitatrichtlijn:

-   **2190_a** - Waterhoudende depressies in vochtige duinvalleien (Denys et al. 2021)
-   **3110** - Mineraalarme oligotrofe wateren van de Atlantische zandvlakten (*Littorelletalia uniflora*) (Decleer 2007, Scheers et al. 2020).
-   **3130** - Oligotrofe tot mesotrofe stilstaande wateren met vegetatie behorend tot de *Littorelletalia uniflora* en/of de *Isoeto-Nanojuncetea* (Decleer 2007, Scheers et al. 2020)
    -   **3130_aom**: subtype aom, subtype oeverkruid (*Littorelletea*)
    -   **3130_na**: subtype na, subtype dwergbiezen (*Isoeto-Nanojuncetea*)
-   **3150** - Van nature eutrofe meren met vegetaties van het type *Magnopotamion* of *Hydrocharition* (Decleer 2007, Scheers et al. 2020)
-   **3160** - Dystrofe natuurlijke poelen en meren (Decleer 2007, Scheers et al. 2020)

**Isoëtiden**: laagblijvende rozetbladige planten met stevige, holle, lijn- of priemvormige bladeren bv. knolrus (*Juncus bulbosus*), oeverkruid (*Littorella uniflora*), waterlobelia (*Lobelia dortmanna*), pilvaren (*Pilularia globulifera*), …

**LSVI**: Lokale staat van instandhouding; instrument om lokaal de toestand van een habitattype te evalueren aan de hand van structuur- en vegetatiekenmerken (Oosterlynck et al. 2020).

**Steekproefpunt** of **(veld)locatie**: Voor het habitatkwaliteitsmeetnet (zie verder) komt de steekproefeenheid voor stilstaande wateren overeen met de watervlakkencode (Westra et al., 2022). Dit is het niveau waarop de biotische karakterisatie wordt beoogd. 

## Doelstelling en toepassingsgebied
