# Beperkingen tot de procedure

In sommige omstandigheden kan er geen waterstaal genomen worden:

-   werken aan de waterloop: lopende of net uitgevoerde werken in of aan de waterloop die een dergelijke tijdelijke impact hebben dat de staalname niet representatief is voor de normale toestand (vb. zeer veel omgewoeld slib tijdens ruiming);

-   staalnamepunt onbereikbaar: het staalnamepunt kan onmogelijk worden bereikt;

-   onvoldoende watervoerend/-houdend: Er kunnen geen waterstalen genomen worden bij een zeer laag waterpeil volgens dit protocol (bv. waterdiepte zo laag dat omwoeling van de waterbodem onvermijdbaar is), of een dermate lage waterstand dat het water niet longitudinaal afstroomt. In dit geval dient een andere bemonsteringsmethode te worden toegepast. Een minimale waterdiepte van 10 à 20 cm naargelang de omstandigheden is vereist om volgens dit protocol een staal te nemen.

-   ijsvorming: de volledige waterkolom is bevroren of de dikte van de ijslaag verhindert de staalname;

-   extreem hoog waterpeil of extreem hoge stroomsnelheden: indien de omstandigheden een gevaar vormen voor de veiligheid van de staalnemer(s), kan de procedure niet worden uitgevoerd.

Indien er geen waterstaal genomen kon worden, wordt dit steeds gedocumenteerd op het staalnameformulier. De staalnamelocatie wordt verschoven of vervangen door een andere locatie volgens het unit selection protocol (in voorbereiding).
