# WERKWIJZE

## Uitvoering

1.  Voorbereiding terreinwerk

-   vooraf worden de XY-coördinaten van de staalnamelocatie ingevoerd in een standaard GPS of in een smartphone-applicatie. Dit is het meest stroomafwaarts gelegen punt van het te bemonsteren 100 meter segment van de waterloop, de steekproefeenheid voor het project meetnetten natuurlijk milieu.

-   in juni-september, tijdens een veldbezoek voorafgaand aan de meetcampagne, wordt vastgesteld of het doelhabitat (habitattype 3260) aanwezig is in het waterloopsegment (habitatdefinitie: zie Leyssen et al. 2020 en SVP-403).

### Lokaliseren en documenteren van [staalnamepunt]{.mark}

-   navigeer met behulp van een standaard GPS (nauwkeurigheid ca. 3-5 m) naar de oever van de staalnamelocatie;

-   zoek binnen een afstand van 100 m stroomopwaarts naar een geschikte staalnamepunt en documenteer deze bij een eerste staalnamebezoek (coördinaten met standaard GPS, beschrijving en foto). Meanders worden hierbij best vermeden door slibophoping in de binnenbocht die kan opwarrelen, grote diepte in buitenbocht (veiligheid) en bijzondere stromings- en turbulentiepatronen in de meanders die kunnen leiden tot kwaliteitsverschillen in de genomen stalen. De voorkeur gaat dan uit naar een staalnamepunt, gelegen tussen 2 meanders op maximaal 100 meter van het oorspronkelijke coördinaten van de staalnamelocatie (figuur 1). De voorkeur wordt gegeven aan vegetatieloze of vegetatiearme zones in de waterloop. Verstoring van de planten leidt tot resuspensie van hierop aanwezig sediment, neerslag en aangroei en kan het staal contamineren.

> Figuur \@ref(fig:Figuur1): Schematische voorstelling van de staalnamelocatie (grijze bol), de zoekzone voor een geschikt staalnamepunt (grijze arcering) en het gekozen staalnamepunt (rode lijn), gelegen tussen de meanders op niet meer dan 100 m van het staalnamelocatie.

1.  Secchi-diepte bepalen

> zie deelprotocol (SVP-113)
>
> De secchi-diepte wordt bij voorkeur bepaald in een vegetatieloze of vegetatiearme zone en in het midden van de waterloop. Indien de secchi-schijf door te sterke stroming niet loodrecht naar beneden kan worden gelaten, kan ze verzwaard worden. Indien de waterdiepte te groot is om de secchi-diepte al wadend te bepalen; kan dit vanop een nabijgelegen brug, of vanop een verankerde boot, gebeuren en dient dit gedocumenteerd te worden op het [staalnameformulier in het opmerkingenveld]{.mark}. De waterdiepte waar de secchi-diepte werd bepaald, wordt eveneens genoteerd.

2.  Bepaling stroomsnelheid

> zie deelprotocol (SVP-118): nog te ontwikkelen
>
> De stroomsnelheid wordt op één plaats gemeten voor een algemene kwantitatieve karakterisatie van de stroomsnelheid. Gedetailleerde stroomsnelheidsbepalingen in verschillende segmenten in de dwarsdoorsnede van de waterlopen en op verschillende diepten zijn hier niet vereist.
>
> De stroomsnelheid wordt gemeten op dezelfde plaats als de secchi-bepaling. Kies een nagenoeg recht stuk van de waterloop uit, met min of meer horizontale stroming (parallel met oeverlijn). Submerse vegetatie, grote stenen, vistrappen en andere obstakels moeten vermeden worden omdat dit turbulentie veroorzaakt.
>
> De keuze van waterdiepte voor de stroomsnelheidsbepaling dient bij het ontwikkelen van het deelprotocol (SVP-118) verder uitgewerkt te worden, o.a. gebaseerd op Hartong & Termes (2009), Osté et al. (2013), Stone et al. (2012) en WVDEP (2018). Er zijn verschillende mogelijkheden:

-   De meting gebeurt op de helft van de waterdiepte. Bijv: bij een waterdiepte van 1 m, wordt de meting op 0,5 m diepte uitgevoerd.

-   Bij zeer diepe waterlopen wordt de stroomsnelheidsmeting op ca. 1 m diepte uitgevoerd, omdat de sonde niet dieper geplaatst kan worden (en uit veiligheidsoverwegingen).

-   De meting gebeurt steeds op 0,5 m diepte (vanaf het wateroppervlak gemeten), tenzij de waterloop minder dan 1 m diep is. Dan wordt de meting uitgevoerd op de helft van de waterdiepte.

    1.  Bemonstering waterkolom en het vullen van de recipiënten

> zie deelprotocols (SOP-005 en SVP-114); delen van onderstaande werkwijze kunnen later overgebracht worden naar SVP-114.
>
> Het mengstaal bestaat uit 3 deelstalen, die gesitueerd zijn langs het dwarsprofiel van de waterloop ter hoogte van het gekozen staalnamepunt (figuur 1) op ca. 0,5 meter waterdiepte (figuur 2). Indien de waterloop minder dan 1 meter diep is, wordt het staal genomen op de helft van de waterdiepte. Indien de waterbodem werd omgewoeld bij de bepaling van secchi-diepte of stroomsnelheid, wordt bij geringe stroming een meter stroomopwaarts gewaad voor deze staalname. Bij de staalname moet vermeden worden om waterbodem mee te bemonsteren, of om te woelen. Het staal wordt indien mogelijk genomen in een vegetatieloze of vegetatiearme zone en niet tussen helofyten. Verstoring van de planten leidt tot resuspensie van hierop aanwezig sediment, neerslag en aangroei en kan het staal contamineren. Desgevallend dient dit bij de opmerkingen op het staalnameformulier vermeld te worden (zie verder).
>
> Figuur \@ref(fig:Figuur2): Situering deelstalen (rode stippen in een dwarsprofiel van een waterloop.
>
> Om de deelstalen te kunnen nemen in stromend water op een diepte van 0,5 meter, zijn volgende methoden of materiaal aangewezen (in dalende voorkeur):

-   horizontale waterhapper (type Friedinger, Van Dorn, ...; zie bijlage 10 van Osté et al. 2013): het staal wordt al wadend genomen in de waterloop; eventueel verzwaard indien de waterstroming te sterk is

-   maatbeker (inhoud 2 l): het staal wordt met een maatbeker genomen al wadend in de waterloop. Hierbij keer je de maatbeker om, laat je deze in het water zakken tot ongeveer 50 cm diepte. Vervolgens keer je de maatbeker om, zodat je op deze diepte een staal kan nemen.

-   horizontale waterhapper vanop een brug: het staal wordt vanop een brug genomen op de 3 deellocaties van de dwarssectie. Dit wordt toegepast bij grote waterlopen, waar een brug aanwezig is en indien de waterdiepte te groot is om er door te waden en stalen te nemen. Omwoelen van de waterbodem tijdens de staalname dient vermeden te worden.

```{=html}
<!-- -->
```
-   stok-methode (naar VMM 2020 en bijlage 10 van Osté et al. 2013): Indien de waterdiepte niet toelaat om veilig een staal al wadend te nemen kunnen de deelstalen genomen worden met behulp van een maatbeker of fles, bevestigd aan een (telescopische) stok. Indien mogelijk wordt geschept op de 3 plaatsen van de dwarssectie en wordt het staal voorzichtig verzameld in de emmer waarbij er gelet wordt op een minimale zuurstofinbreng.

De staalnamemethode wordt genoteerd op het veldformulier.

### Uitvoering veldmetingen

### zie deelprotocol (SVP-115) {#zie-deelprotocol-svp-115 .unnumbered}

1.  Aflevering stalen aan het labo

### De gekoeld getransporteerde stalen, inclusief een kopie van het staalnameformulier, worden zo snel mogelijk en zeker binnen de tijdspanne van 24 uur na het nemen van het eerste staal van de dag binnengebracht bij het labo. In het labo worden de stalen, in afwachting van verdere analyse, in de koelkamer bewaard (zie SVP-007). {#de-gekoeld-getransporteerde-stalen-inclusief-een-kopie-van-het-staalnameformulier-worden-zo-snel-mogelijk-en-zeker-binnen-de-tijdspanne-van-24-uur-na-het-nemen-van-het-eerste-staal-van-de-dag-binnengebracht-bij-het-labo.-in-het-labo-worden-de-stalen-in-afwachting-van-verdere-analyse-in-de-koelkamer-bewaard-zie-svp-007. .unnumbered}

2.  Digitalisatie van de gegevens op het staalnameformulier

> Na de staalname worden de gegevens ingevoerd in het digitale staalnameformulier gedeeld door het Labo via Google Drive.

## Registratie en bewaring van resultaten

### Registratie van resultaten: [staalnameformulier]{.mark} (naar VMM 2020)

Het [staalnameformulier]{.mark} kan ingedeeld worden in 3 onderdelen (zie google sheet Bijlage 1):

1\. kopgegevens: labocode (vooraf ingevuld), code [staalnamepunt]{.mark}, staalnemer, datum, uur

-   reden geen staalname: werken waterloop; [staalnamepunt]{.mark} onbereikbaar; onvoldoende watervoerend/-houdend; ijsvorming (omschrijving: zie hoger)

-   staalnamepunt: in waterloop (afgekort WL); vanop brug/duiker; vanop steiger

-   staalnamemethode: horizontale waterhapper; maatbeker; telescopische stok

-   weersomstandigheden: hevige neerslag, geen neerslag, ...

De staalnamepunt en staalnamemethode wordt genoteerd zodat toekomstige staalnames zoveel mogelijk op dezelfde wijze gebeuren en de meetresultaten vergelijkbaar zijn.

2\. veldmetingen: temperatuur (°C), pH, EC (µS/cm), saliniteit (g/kg), O~2~ (mg/l), O~2~-saturatie (%), secchi-diepte (SD, m), waterdiepte (WD, m), stroomsnelheid (ss, m/s)

3\. uitzonderlijke omstandigheden

Deze veldwaarnemingen omvatten waarnemingen ter plaatse, of in de onmiddellijke omgeving van het [staalnamepunt, van tijdelijke fenomenen]{.mark} waarvoor een verband met de abiotische toestand van de onderzochte waterloop vermoed kan worden. Het gaat om vaststellingen die afwijkend zijn van de normale omstandigheden. Omdat deze mede de analyseresultaten kunnen verklaren is het van belang dat ze zo uniform mogelijk en kwaliteitsvol worden ingevuld. Op het [staalnameformulier]{.mark} wordt bij veldwaarnemingen onderstaande onderlijnde uitspraak genoteerd bij 'uitzonderlijke veldwaarnemingen'. Onderstaande lijst kan op een klembord gekleefd worden als geheugensteun.

-   zichtbare verontreiniging van wateroppervlak of waterkolom:

    -   [Maaisel]{.underline} / drijvende plantenresten: op het wateroppervlak drijft er maaisel of zijn er drijvende plantenresten aanwezig.

    -   [Dode fauna]{.underline}: dode fauna aanwezig (vis, eend, ...).

    -   [Olie]{.underline}: kleurige film (kleurschakering met rood, paars, blauw en geel) op het wateroppervlak. Opgelet: bacteriën kunnen eveneens een dunne film op het water vormen. Bij verstoring van deze film (bv door de inworp van een steen) zal deze laag echter breken in de vorm van barstjes, terwijl een oliefilm zich bijna onmiddellijk terug sluit.

    -   Vast [afval]{.underline}: zoals bv. flessen, banden, fietsen, plastic zakken, blikjes,... .

    -   [Schuim]{.underline}: schuimvorming ten gevolge van algenbloei of tensio-actief schuim (veroorzaakt door detergenten).

    -   [Algenbloei]{.underline}: het water heeft meestal een groene kleur (, in de duidelijkste gevallen te omschrijven als 'erwtensoep'; kan ook gepaard gaan met bv. een bruine, blauwe, paarse of rode kleur.

    -   Bloei [watervlooi]{.underline}en: dit kan het water rood kleuren. Het waterstaal bevat veel zoöplankton als men ziet dat de rode massa kleine beweeglijke organismen zijn.

    -   [Gas]{.underline}ontwikkeling: aan het wateroppervlak ziet men kleine blaasjes (gasbellen) die openbarsten.

    -   [Vlok]{.underline}ken: samengekoekt materiaal (groot of klein) met onregelmatige structuur in of op de waterkolom (meestal wit, grijs of zwart).

    -   [Rioolschimmel]{.underline}: grijze tot bruine slierten (schimmels) op wortels, stenen of de bodem.

-   [Abundante plantengroei]{.underline}, waardoor de staalname bemoeilijkt wordt.

-   Andere opmerkingen: wordt ingevuld indien geen van de overige codes van toepassing is.

### Bewaring van resultaten

-   Voor elk [staalnamepunt]{.mark} wordt ter plaatse een analoog [staalnameformulier]{.mark} ingevuld (zie hoger). Afwijkingen van de beschreven werkwijze voor het nemen van een schepstaal worden eveneens genoteerd.

-   De meetresultaten, vermeld op het [staalnameformulier]{.mark}, worden zo snel mogelijk gedigitaliseerd en gedeeld met het labo.

```{=html}
<!-- -->
```
-   De laboresultaten worden geregistreerd in LIMS en worden ontsloten via het LIMS-datawarehouse.

### Opslag van foto's

> Opslag van foto's op google drive met aanduiding van opnamedatum, code [staalnamepunt]{.mark} en naam waterloop (volgens de Vlaamse Hydrografische Atlas; [[https://www.vmm.be/data/vlaamse-hydrografische-atlas]{.underline}](https://www.vmm.be/data/vlaamse-hydrografische-atlas)).

