# SAMENVATTING

Een samenvattende opsomming van de te volgen stappen:

1.  controleer de lijst met benodigdheden en het niveau van de batterijen voor vertrek;

2.  navigeer met een GPS naar de staalnamelocatie, beoordeel de situatie ter plekke;

3.  kies een geschikt staalnamepunt en documenteer deze (foto's);

4.  bepaal de secchi- en waterdiepte volgens het protocol SVP-113;

5.  bepaal de stroomsnelheid volgens het protocol SVP-118;

6.  spoel het materiaal voor met water van het staalnamepunt en neem een mengstaal volgens protocol SVP-114;

7.  neem met de maatbeker een substaal van het mengstaal en voer de veldmeting uit volgens het protocol SVP-115;

8.  vul en bewaar de recipiënten voor het laboratorium volgens het protocol SVP-114 met het overige mengstaal;

9.  reinig het gebruikte materiaal;

10. controleer of het [staalnameformulier]{.mark} volledig is ingevuld, voeg eventuele uitzonderlijke veldwaarnemingen toe;

11. breng de stalen en een kopie van het [staalnameformulier]{.mark} binnen bij het labo (binnen 24u na het nemen van het eerste staal);

12. digitaliseer het staalnameformulier en klasseer de foto's.

