# Beperkingen tot de procedure

In bepaalde omstandigheden kan er geen waterstaal genomen worden.

-   bepaalde activiteiten in het water of op de oever kunnen tijdelijk een zodanig grote impact hebben op de toestand van de waterkolom dat staalname niet zinvol of wenselijk is (vb. zeer veel omgewoeld slib tijdens slibruiming);

-   [het staalnamepunt]{.mark} kan onmogelijk worden bereikt;

-   gedeeltelijk of geheel droogvallen van de staalnameplaats. Er kunnen geen waterstalen genomen worden bij een te laag waterpeil. Bij een waterdiepte minder dan 0,05 m is omwoeling van de waterbodem nagenoeg onvermijdelijk[^1];

-   bij een bevroren wateroppervlak kan een ijslaag de staalname verhinderen wanneer deze te dik is om te breken. Bij diepere plassen is staalname bij ijsvorming niet mogelijk als de veiligheid van de staalnemer niet gegarandeerd kan worden. Indien het breken van de ijslaag in zeer ondiep water zou leiden tot het omwoelen van de waterbodem is het nemen van een waterstaal niet mogelijk;

-   tijdens en vlak na overstroming kan het staalnamepunt onbereikbaar zijn of kan door het aandeel gebiedsvreemd water, staalname niet zinvol/wenselijk zijn;

-   bepaalde weersomstandigheden waarin de veiligheid van de staalnemer niet kan gegarandeerd worden (storm, bliksem, etc.) kunnen staalname onmogelijk maken.

Naast de hierboven opgesomde beperkingen kunnen er nog extra beperkingen zijn voor het uitvoeren van specifieke deelprotocollen. Voor deze deelprotocolspecifieke beperkingen verwijzen we naar de deelprotocollen SVP-113, SVP-114 en SVP-115. De beperkende factoren die de staalname bemoeilijken of verhinderen worden steeds gedocumenteerd in het opmerkingenveld op het [staalnameformulier]{.mark}.

