# BENODIGDHEDEN

Tabel \@ref(tab:Tabel1) geeft een overzicht van de benodigde apparatuur en materiaal voor het uitvoeren van een abiotische staalname. Onder 5.1, 5.2 en 5.3 worden een aantal specifieke benodigdheden van verdere uitleg voorzien.

Table: (#tab:Tabel1) Checklist benodigd veldmateriaal.

  -----------------------------------------------------------------------------------------------------------------
  **Algemene benodigdheden**                                     **Specifieke benodigdheden deelprotocollen**
  -------------------------------------------------------------- --------------------------------------------------
  ◻ staalnameformulier                                           ◻ staalname-emmer (SVP-114, SVP-115)

  ◻ klembord, potlood en slijper                                 ◻ maatbeker (SVP-114, SVP-115)

  ◻ laarzen, lieslaarzen, waadpak (site-afhankelijk)             ◻ spuiten en filters (SVP-114)

  ◻ latex handschoenen (poederloos)                              ◻ recipiënten (SVP-114)

  ◻ plooimeter                                                   ◻ extra recipiënt, hersluitbare zakjes (SVP-114)

  ◻ fototoestel                                                  ◻ koelbox met koelelementen (SVP-114)

  ◻ documentatie lokalisatie staalnamepunt                       ◻ Secchi-schijf (SVP-113)

  ◻ relevante protocollen (SVP-113, SVP-114, SVP-115, SPP-116)   ◻ veldmeter type WTW Multi 3430 (SVP-115)

                                                                 ◻ spuitfles met ultrapuur water (UPW) (SVP-115)
  -----------------------------------------------------------------------------------------------------------------

## Apparatuur

Zie apparatuur van de deelprotocol SVP-115.

## Materiaal

Het materiaal en de apparatuur vermeld in de deelprotocollen SVP-113, SVP-114 en SVP-115 zijn opgelijst in tabel 1. Voor meer informatie en een beschrijving van dit materiaal en apparatuur verwijzen we naar deze deelprotocollen zelf.

**5.2.1 Locatieafhankelijke benodigdheden**

Afhankelijk van de diepte en aard van de staalnamelocatie en de ligging van het staalnamepunt kunnen laarzen, lieslaarzen, waadpak en in bepaalde gevallen zelfs een boot nodig zijn. Bij werk vanop een boot of bij steile oevers kan een zwemvest en/of reddingstouw aangeraden of verplicht zijn (zie protocol SVP-112: Veiligheid in en rond water).

**5.2.2 Staalnameformulier**

Het staalnameformulier (bijlage 1) kan zowel digitaal als analoog ingevuld worden in het veld. Bij voorkeur wordt tijdens de staalname steeds de analoge versie ingevuld, zodat typfouten of problemen bij het opslaan niet mogelijk zijn en tevens een originele versie wordt bewaard om controle op een later tijdstip mogelijk te maken. Het staalnameformulier wordt duidelijk leesbaar en volledig ingevuld met potlood.

Op het staalnameformulier worden tijdens de abiotische staalname (volgens het voorgelegde protocol) de volgende gegevens ingevuld:

-   code van het staal (= Labo ID);

-   code van de locatie (= Veld ID);

-   staalnemer;

-   datum staalname (jjjj/mm/dd);

-   temperatuur (°C);

-   zuurtegraad (pH) (eq/l);

-   conductiviteit (EC) (in µS/cm bij lage waarden of mS/cm bij hoge waarden);

-   saliniteit (g/kg);

-   opgeloste zuurstof (mg/l);

-   zuurstofverzadiging (%);

-   opmerkingenveld.

## Reagentia en oplossingen 

Zie reagentia en oplossingen van het deelprotocol SVP-114 (Bemonstering waterkolom oppervlaktewater adhv van een waterstaal) en SVP-115 (Veldmeting abiotiek oppervlaktewater m.b.v. veldmeter WTW Multi 3430)

