# Samenvatting

Een samenvattende opsomming van de te volgen stappen:

1.  controleer de lijst met benodigdheden voor vertrek;

2.  navigeer met behulp van kaartmateriaal en/of een GPS naar de staalnamelocatie en lokaliseer het staalnamepunt (of selecteer een geschikt staalnamepunt indien nog niet vastgelegd);

3.  vastleggen toestand staalnamelocatie (op staalnameformulier en documenteer met één of meerdere foto's);

4.  spoel het materiaal voor met water van het staalnamepunt;

5.  neem een mengstaal volgens protocol SVP-114;

6.  neem met de maatbeker een substaal van het mengstaal en voer de veldmeting uit met de digitale veldmeter type WTW Multi 3430 volgens het protocol SVP-115;

7.  vul de recipiënten voor het laboratorium (protocol SVP-114) met het overige mengstaal:

    1.  Vul het recipiënt voor IPC met spuit en filters;

    2.  Vul de overige recipiënten;

8.  steek de gevulde recipiënten per staalnamepunt samen in een zakje met gripsluiting en bewaar deze in de koelbox (protocol SVP-114);

9.  bepaal de secchi-diepte en waterdiepte volgens protocol SVP-113;

10. reinig het gebruikte materiaal;

11. controleer of het staalnameformulier volledig is ingevuld, voeg eventuele uitzonderlijke veldwaarnemingen toe;

12. breng de stalen en een kopie van het staalnameformulier binnen bij het labo (binnen 24u na nemen van het eerste staal);

13. digitaliseer het staalnameformulier en klasseer de foto's (registratie)
