# REFERENTIES

Bijkerk R. (red) (2014). Handboek Hydrobiologie. Biologisch onderzoek voor de ecologische beoordeling van Nederlandse zoete en brakke oppervlaktewateren. Deels aangepaste versie (Rapport 2014 - 02). Stichting Toegepast Onderzoek Waterbeheer, Amersfoort.

DIW (2003). Decreet Integraal Waterbeleid van 18 juli 2003 (B.S. 5/12/2003). [[https://navigator.emis.vito.be/mijn-navigator?woId=75697]{.underline}](https://navigator.emis.vito.be/mijn-navigator?woId=75697)

Scheers K., Packet J., Denys L., Smekens V., De Saeger S. (2016). BWK en habitatkartering, een praktische handleiding. Deel 3: handleiding voor het typeren van de stilstaande wateren in Vlaanderen. Versie 1. Rapporten Instituut voor Natuur- en Bosonderzoek INBO.R.2016. 11613720

Vanderhaeghe F., Adriaens D., Denys L., Cools N., Jansen I., Herr C., Verstraeten A., Raman M., Wouters J.,Van Calster H. Westra T., Onkelinx T., Van Daele T., Oosterlynck P., Leyssen A., Wackenier M., De Becker P., Piesschaert F., Desmet P., Louette G., Quataert P., Vandenabeele, M.A., Van Elegem B. (2020). Ontwikkeling en implementatie meetnetten natuurlijk milieu. In: Programmatorische aanpak stikstof -- platform passende beoordeling. Onderzoek, monitoring, methodologie-ontwikkeling en data-ontsluiting door het Instituut voor Natuur- en Bosonderzoek (PAS-PPB periode 2015-2019). Hoffmann M. & Gerald Louette G. (eds.). Rapporten van het Instituut voor Natuur- en Bosonderzoek (11), Brussel. blz. 106-116.

**Bijlage 1. Voorbeeld staalnameformulier.**

  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  **VELDFORMULIER WATER**                                                                                                                                                                                       
  ------------------------- --------------------- ---------------- -------------------- ----------------------------------------- ---------------- ---------------- ------------ ------ ------------- ---- ---- --------------
  **Project:**              **Project:**                                                **Print Datum:**                                                                                                        

  **Projectverantw.**       **Projectverantw.**                                         **Verwachte datum binnenkomst stalen:**                                                                                 

  Staal ID                  Staal ID              Monsternemer     Datum bemonstering   Temp                                      pH               EC               Saliniteit   O2     Saturatie     SD   WD   Opmerkingen

  Labo ID                   Veld ID               xx               jjjj/mm/dd           °C                                                         µS/cm            g/kg         mg/l   \%            m    m    

  NA                        NA                    volledige naam                                                                  4,95\<pH\<5,05   1399\<EC\<1428                       99\<O2\<101             

  Controle Start                                                                                                                                                                                                

  Controle Eind                                                                                                                                                                                                 

                                                                                                                                                                                                                

                                                                                                                                                                                                                

                                                                                                                                                                                                                

                                                                                                                                                                                                                

                                                                                                                                                                                                                

                                                                                                                                                                                                                

                                                                                                                                                                                                                

                                                                                                                                                                                                                

                                                                                                                                                                                                                
  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

[^1]: Indien gewenst kan beroep worden gedaan op een andere bemonsteringsmethode.

[^2]:  Aquamorf databank: interne databank met plaatskenmerken van stilstaande wateren in Vlaanderen. In deze databank zijn alle staalnamepunten terug te vinden in de shapefile 'waterstaal'.

