<!DOCTYPE html>
<html >

<head>
<meta name="protocol-title" content="Veldprotocol LSVI-bepaling stilstaande wateren" />
<meta name="protocol-subtitle" content="LSVI stilstaande wateren" />
<meta name="protocol-code" content="sfp-402-nl" />
<meta name="protocol-version" content="2025.01" />
<meta name="protocol-language" content="" />
<meta name="protocol-theme" content="" />
<meta name="protocol-reviewer" content="true" />
<meta name="protocol-file-manager" content="true" />

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Veldprotocol LSVI-bepaling stilstaande wateren</title>
  <meta name="description" content="Veldprotocol LSVI-bepaling stilstaande wateren">
  <meta name="generator" content="bookdown  and GitBook 2.6.7">

  <meta property="og:title" content="Veldprotocol LSVI-bepaling stilstaande wateren" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Veldprotocol LSVI-bepaling stilstaande wateren" />
  
  
  



<meta name="date" content="2025-10-10">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  


<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>



<link rel="stylesheet" href="css/inbo_rapport.css" type="text/css"/>

<link rel="stylesheet" href="css/inbo_rapport.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">

      <nav role="navigation">

<ul class="summary">
<li class="toc-logo"><a href="https://www.vlaanderen.be/inbo/home/"><img src="css/img/inbo-nl.jpg"></a></li>
<li class="toc-logo"><a href="https://inbo.github.io/protocols/"><button class="btn"><i class="fa fa-home"></i> Protocols homepage</button></li>
<li class="divider"></li>
<li class="chapter" data-level="" data-path=""><a href="#metadata"><i class="fa fa-check"></i>Metadata</a></li>
<li class="chapter" data-level="1" data-path=""><a href="#wijzigingen-t.o.v.-vorige-versies"><i class="fa fa-check"></i><b>1</b> Wijzigingen t.o.v. vorige versies</a>
<ul>
<li class="chapter" data-level="1.1" data-path=""><a href="#section"><i class="fa fa-check"></i><b>1.1</b> 2025.01</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path=""><a href="#afhankelijkheden"><i class="fa fa-check"></i><b>2</b> Afhankelijkheden</a></li>
<li class="chapter" data-level="3" data-path=""><a href="#onderwerp"><i class="fa fa-check"></i><b>3</b> Onderwerp</a>
<ul>
<li class="chapter" data-level="3.1" data-path=""><a href="#definities-en-afkortingen"><i class="fa fa-check"></i><b>3.1</b> Definities en afkortingen</a></li>
<li class="chapter" data-level="3.2" data-path=""><a href="#doelstelling-en-toepassingsgebied"><i class="fa fa-check"></i><b>3.2</b> Doelstelling en toepassingsgebied</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path=""><a href="#beperkingen-van-het-protocol-sec-beperkingen"><i class="fa fa-check"></i><b>4</b> Beperkingen van het protocol {#sec: beperkingen}</a></li>
<li class="chapter" data-level="5" data-path=""><a href="#principe"><i class="fa fa-check"></i><b>5</b> Principe</a></li>
<li class="chapter" data-level="6" data-path=""><a href="#vereiste-competenties"><i class="fa fa-check"></i><b>6</b> Vereiste competenties</a></li>
<li class="chapter" data-level="7" data-path=""><a href="#benodigdheden"><i class="fa fa-check"></i><b>7</b> Benodigdheden</a>
<ul>
<li class="chapter" data-level="7.1" data-path=""><a href="#apparatuur"><i class="fa fa-check"></i><b>7.1</b> Apparatuur</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path=""><a href="#binoculaire-stereomicroscoop-enof-lichtmicroscoop"><i class="fa fa-check"></i><b>7.1.1</b> Binoculaire stereomicroscoop en/of lichtmicroscoop</a></li>
<li class="chapter" data-level="7.1.2" data-path=""><a href="#gps"><i class="fa fa-check"></i><b>7.1.2</b> GPS</a></li>
<li class="chapter" data-level="7.1.3" data-path=""><a href="#handcomputer-of-tablet-optioneel"><i class="fa fa-check"></i><b>7.1.3</b> Handcomputer of tablet (optioneel)</a></li>
<li class="chapter" data-level="7.1.4" data-path=""><a href="#sonarapparatuur-bij-bootwerk"><i class="fa fa-check"></i><b>7.1.4</b> Sonarapparatuur (bij bootwerk)</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path=""><a href="#materiaal"><i class="fa fa-check"></i><b>7.2</b> Materiaal</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path=""><a href="#veldloep"><i class="fa fa-check"></i><b>7.2.1</b> Veldloep</a></li>
<li class="chapter" data-level="7.2.2" data-path=""><a href="#vegetatiehark-met-telescopische-steel"><i class="fa fa-check"></i><b>7.2.2</b> Vegetatiehark met telescopische steel</a></li>
<li class="chapter" data-level="7.2.3" data-path=""><a href="#dubbelzijdige-dreghark"><i class="fa fa-check"></i><b>7.2.3</b> Dubbelzijdige dreghark</a></li>
<li class="chapter" data-level="7.2.4" data-path=""><a href="#hersluitbare-zakjes-en-alcoholstift"><i class="fa fa-check"></i><b>7.2.4</b> Hersluitbare zakjes en (alcohol)stift</a></li>
<li class="chapter" data-level="7.2.5" data-path=""><a href="#secchi-schijf"><i class="fa fa-check"></i><b>7.2.5</b> Secchi-schijf</a></li>
<li class="chapter" data-level="7.2.6" data-path=""><a href="#plooimeter"><i class="fa fa-check"></i><b>7.2.6</b> Plooimeter</a></li>
<li class="chapter" data-level="7.2.7" data-path=""><a href="#determinatiewerken"><i class="fa fa-check"></i><b>7.2.7</b> Determinatiewerken</a></li>
<li class="chapter" data-level="7.2.8" data-path=""><a href="#boot"><i class="fa fa-check"></i><b>7.2.8</b> Boot</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path=""><a href="#reagentia-en-oplossingen-indien-van-toepassing"><i class="fa fa-check"></i><b>7.3</b> Reagentia en oplossingen (indien van toepassing)</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path=""><a href="#werkwijze"><i class="fa fa-check"></i><b>8</b> Werkwijze</a>
<ul>
<li class="chapter" data-level="8.1" data-path=""><a href="#uitvoering"><i class="fa fa-check"></i><b>8.1</b> Uitvoering</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path=""><a href="#voorafgaand-aan-het-terreinwerk"><i class="fa fa-check"></i><b>8.1.1</b> Voorafgaand aan het terreinwerk</a></li>
<li class="chapter" data-level="8.1.2" data-path=""><a href="#lokaliseren-en-documenteren-van-veldlocatie"><i class="fa fa-check"></i><b>8.1.2</b> Lokaliseren en documenteren van veldlocatie</a></li>
<li class="chapter" data-level="8.1.3" data-path=""><a href="#bepaling-aanwezige-habitattypen"><i class="fa fa-check"></i><b>8.1.3</b> Bepaling aanwezige habitattypen</a></li>
<li class="chapter" data-level="8.1.4" data-path=""><a href="#vegetatieopname-sec-vegetatieopname"><i class="fa fa-check"></i><b>8.1.4</b> Vegetatieopname {#sec: vegetatieopname}</a></li>
<li class="chapter" data-level="8.1.5" data-path=""><a href="#bedekking-van-groepen-van-soorten"><i class="fa fa-check"></i><b>8.1.5</b> Bedekking van groepen van soorten</a></li>
<li class="chapter" data-level="8.1.6" data-path=""><a href="#structuurkenmerken"><i class="fa fa-check"></i><b>8.1.6</b> Structuurkenmerken</a></li>
<li class="chapter" data-level="8.1.7" data-path=""><a href="#algemene-standplaatskenmerken"><i class="fa fa-check"></i><b>8.1.7</b> Algemene standplaatskenmerken</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path=""><a href="#registratie-en-bewaring-van-resultaten"><i class="fa fa-check"></i><b>8.2</b> Registratie en bewaring van resultaten</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path=""><a href="#invoer-veldgegevens"><i class="fa fa-check"></i><b>8.2.1</b> Invoer veldgegevens</a></li>
<li class="chapter" data-level="8.2.2" data-path=""><a href="#determinaties"><i class="fa fa-check"></i><b>8.2.2</b> Determinaties</a></li>
<li class="chapter" data-level="8.2.3" data-path=""><a href="#opslag-van-fotos"><i class="fa fa-check"></i><b>8.2.3</b> Opslag van foto’s</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path=""><a href="#kwaliteitszorg"><i class="fa fa-check"></i><b>9</b> Kwaliteitszorg</a></li>
<li class="chapter" data-level="10" data-path=""><a href="#veiligheid"><i class="fa fa-check"></i><b>10</b> Veiligheid</a></li>
<li class="chapter" data-level="11" data-path=""><a href="#samenvatting"><i class="fa fa-check"></i><b>11</b> Samenvatting</a></li>
<li class="chapter" data-level="" data-path=""><a href="#referenties"><i class="fa fa-check"></i>Referenties</a></li>
<li class="chapter" data-level="12" data-path=""><a href="#appendix-bijlagen-.unnumbered-sec-bijlage"><i class="fa fa-check"></i><b>12</b> (APPENDIX) Bijlagen {.unnumbered} {#sec: bijlage}</a>
<ul>
<li class="chapter" data-level="12.1" data-path=""><a href="#bijlage-1-determinatiewerken-sec-bijlage1"><i class="fa fa-check"></i><b>12.1</b> Bijlage 1: Determinatiewerken {#sec: bijlage1}</a>
<ul>
<li class="chapter" data-level="12.1.1" data-path=""><a href="#algemene-floras"><i class="fa fa-check"></i><b>12.1.1</b> Algemene flora’s</a></li>
<li class="chapter" data-level="12.1.2" data-path=""><a href="#ge%C3%AFllustreerde-floras"><i class="fa fa-check"></i><b>12.1.2</b> Geïllustreerde flora’s</a></li>
<li class="chapter" data-level="12.1.3" data-path=""><a href="#atlas"><i class="fa fa-check"></i><b>12.1.3</b> Atlas</a></li>
<li class="chapter" data-level="12.1.4" data-path=""><a href="#herkenning-van-water--enof-oeverplanten"><i class="fa fa-check"></i><b>12.1.4</b> Herkenning van water- en/of oeverplanten</a></li>
<li class="chapter" data-level="12.1.5" data-path=""><a href="#gerichte-determinatiewerken"><i class="fa fa-check"></i><b>12.1.5</b> Gerichte determinatiewerken</a></li>
<li class="chapter" data-level="12.1.6" data-path=""><a href="#artikels"><i class="fa fa-check"></i><b>12.1.6</b> Artikels</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path=""><a href="#bijlage-2-veldformulier-habitattype-2190_a-sec-bijlage2"><i class="fa fa-check"></i><b>12.2</b> Bijlage 2: Veldformulier habitattype 2190_a {#sec: bijlage2}</a></li>
<li class="chapter" data-level="12.3" data-path=""><a href="#bijlage-3-veldformulier-habitattype-3110-sec-bijlage3"><i class="fa fa-check"></i><b>12.3</b> Bijlage 3: Veldformulier habitattype 3110 {#sec: bijlage3}</a></li>
<li class="chapter" data-level="12.4" data-path=""><a href="#bijlage-4-veldformulier-habitattype-3130_aom-sec-bijlage4"><i class="fa fa-check"></i><b>12.4</b> Bijlage 4: Veldformulier habitattype 3130_aom {#sec: bijlage4}</a></li>
<li class="chapter" data-level="12.5" data-path=""><a href="#bijlage-5-veldformulier-habitattype-3130_na-sec-bijlage5"><i class="fa fa-check"></i><b>12.5</b> Bijlage 5: Veldformulier habitattype 3130_na {#sec: bijlage5}</a></li>
<li class="chapter" data-level="12.6" data-path=""><a href="#bijlage-6-veldformulier-habitattype-3140-sec-bijlage6"><i class="fa fa-check"></i><b>12.6</b> Bijlage 6: Veldformulier habitattype 3140 {#sec: bijlage6}</a></li>
<li class="chapter" data-level="12.7" data-path=""><a href="#bijlage-7-veldformulier-habitattype-3150-sec-bijlage7"><i class="fa fa-check"></i><b>12.7</b> Bijlage 7: Veldformulier habitattype 3150 {#sec: bijlage7}</a></li>
<li class="chapter" data-level="12.8" data-path=""><a href="#bijlage-8-veldformulier-habitattype-3160-sec-bijlage8"><i class="fa fa-check"></i><b>12.8</b> Bijlage 8: Veldformulier habitattype 3160 {#sec: bijlage8}</a></li>
</ul></li>
<li class="divider"></li>
<li class="cc"><a href="http://creativecommons.org/licenses/by/4.0/"><img src="css/img/cc-by.png"></a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Veldprotocol LSVI-bepaling stilstaande wateren</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
  <div id="header">
    <h1 class="title">Veldprotocol LSVI-bepaling stilstaande wateren</h1>
      <h2 class="subtitle">LSVI stilstaande wateren</h2>
        <h3 class="author">An Leyssen
          <a href="https://orcid.org/0000-0003-3537-286X">
      <img alt="ORCID logo" src="https://info.orcid.org/wp-content/uploads/2019/11/orcid_16x16.png" width="16" height="16" />
      0000-0003-3537-286X
      </a>
        </h3>
          <address class="author_afil">
      Instituut voor Natuur- en Bosonderzoek (INBO)
              <br><a class="author_email" href="mailto:#"><a href="mailto:an.leyssen@inbo.be" class="email">an.leyssen@inbo.be</a></a>
            </address>
          <h3 class="author">Vincent Smeekens
          <a href="https://orcid.org/0000-0003-2996-2716">
      <img alt="ORCID logo" src="https://info.orcid.org/wp-content/uploads/2019/11/orcid_16x16.png" width="16" height="16" />
      0000-0003-2996-2716
      </a>
        </h3>
          <address class="author_afil">
      Instituut voor Natuur- en Bosonderzoek (INBO)
              <br><a class="author_email" href="mailto:#"><a href="mailto:vincent.smeekens@inbo.be" class="email">vincent.smeekens@inbo.be</a></a>
            </address>
          <h3 class="author">Jo Packet
          <a href="https://orcid.org/0000-0001-5590-323X">
      <img alt="ORCID logo" src="https://info.orcid.org/wp-content/uploads/2019/11/orcid_16x16.png" width="16" height="16" />
      0000-0001-5590-323X
      </a>
        </h3>
          <address class="author_afil">
      Instituut voor Natuur- en Bosonderzoek (INBO)
              <br><a class="author_email" href="mailto:#"><a href="mailto:jo.packet@inbo.be" class="email">jo.packet@inbo.be</a></a>
            </address>
          <h3 class="author">Kevin Scheers
          <a href="https://orcid.org/0000-0002-4756-4247">
      <img alt="ORCID logo" src="https://info.orcid.org/wp-content/uploads/2019/11/orcid_16x16.png" width="16" height="16" />
      0000-0002-4756-4247
      </a>
        </h3>
          <address class="author_afil">
      Instituut voor Natuur- en Bosonderzoek (INBO)
              <br><a class="author_email" href="mailto:#"><a href="mailto:kevin.scheers@inbo.be" class="email">kevin.scheers@inbo.be</a></a>
            </address>
          <h3 class="author">Florian Van Hecke
          <a href="https://orcid.org/0009-0004-3499-2279">
      <img alt="ORCID logo" src="https://info.orcid.org/wp-content/uploads/2019/11/orcid_16x16.png" width="16" height="16" />
      0009-0004-3499-2279
      </a>
        </h3>
          <address class="author_afil">
      Instituut voor Natuur- en Bosonderzoek (INBO)
              <br><a class="author_email" href="mailto:#"><a href="mailto:florian.vanhecke@inbo.be" class="email">florian.vanhecke@inbo.be</a></a>
            </address>
            <p class="date"><em>2025-10-10</em></p>
      
<!--
Instructies bij opmaak van het protocol:

Hieronder vind je de verschillende onderdelen van een protocol.
In de bijhorende losse `Rmd` bestanden vind je een beschrijving wat er bij elk onderdeel vermeld moet worden.
Het is in die bestanden dat je moet editeren.
Niet alle onderdelen zijn altijd van toepassing.
Laat in die gevallen de titels staan en vermeld expliciet "niet van toepassing".
-->
<div id="metadata" class="section level1 unnumbered hasAnchor">
<h1>Metadata<a href="#metadata" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<table>
<colgroup>
<col width="14%" />
<col width="24%" />
<col width="18%" />
<col width="18%" />
<col width="8%" />
<col width="15%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">reviewers</th>
<th align="left">documentbeheerder</th>
<th align="left">protocolcode</th>
<th align="left">versienummer</th>
<th align="left">taal</th>
<th align="left">thema</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">NULL NULL</td>
<td align="left">Toon Westra</td>
<td align="left">sfp-402-nl</td>
<td align="left">2025.01</td>
<td align="left">nl</td>
<td align="left">vegetation</td>
</tr>
</tbody>
</table>
<p>Controleer <a href="../standard-field-protocols-sfp.html" target="_blank">deze tabel</a> om te zien of een meer recente versie beschikbaar is.</p>

</div>
<div id="wijzigingen-t.o.v.-vorige-versies" class="section level1 hasAnchor" number="1">
<h1><span class="header-section-number">1</span> Wijzigingen t.o.v. vorige versies<a href="#wijzigingen-t.o.v.-vorige-versies" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="section" class="section level2 hasAnchor" number="1.1">
<h2><span class="header-section-number">1.1</span> <a href="../2025.01/index.html">2025.01</a><a href="#section" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ul>
<li>…</li>
</ul>
<!--
Omschrijf hier welke wijzigingen er gebeurd zijn ten opzichte van de vorige versie. 
Vermeld bij elk versienummer, de reden van de wijziging en - wanneer relevant - een beknopte beschrijving van de wijziging.
Gesorteerd van recent naar oud. 

## [2020.02](../2020.02/index.html)

- Toevoeging van ontbrekende stap in het stappenplan
- Verbetering van schrijffouten

## [2020.01](../2020.01/index.html)

- Eerste versie van het protocol
-->

</div>
</div>
<div id="afhankelijkheden" class="section level1 hasAnchor" number="2">
<h1><span class="header-section-number">2</span> Afhankelijkheden<a href="#afhankelijkheden" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<!--
Hier niets invullen.
Indien er afhankelijkheden zijn deze invullen in de yaml sectie van `index.Rmd`
-->
<table style="width:93%;">
<colgroup>
<col width="20%" />
<col width="20%" />
<col width="12%" />
<col width="38%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Protocolcode</th>
<th align="left">Versienummer</th>
<th align="left">params</th>
<th align="left">Opgenomen als subprotocol</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
</tr>
</tbody>
</table>

</div>
<div id="onderwerp" class="section level1 hasAnchor" number="3">
<h1><span class="header-section-number">3</span> Onderwerp<a href="#onderwerp" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="definities-en-afkortingen" class="section level2 hasAnchor" number="3.1">
<h2><span class="header-section-number">3.1</span> Definities en afkortingen<a href="#definities-en-afkortingen" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><strong>31xx</strong>: afkorting voor Natura2000-habitattypen 3110, 3130, 3140, 3150 en 3160</p>
<p><strong>Habitattypen</strong> van stilstaand water die beschermd zijn door de habitatrichtlijn:</p>
<ul>
<li><strong>2190_a</strong> - Waterhoudende depressies in vochtige duinvalleien (Denys et al. 2021)</li>
<li><strong>3110</strong> - Mineraalarme oligotrofe wateren van de Atlantische zandvlakten (<em>Littorelletalia uniflora</em>) (Decleer 2007, Scheers et al. 2020).</li>
<li><strong>3130</strong> - Oligotrofe tot mesotrofe stilstaande wateren met vegetatie behorend tot de <em>Littorelletalia uniflora</em> en/of de <em>Isoeto-Nanojuncetea</em> (Decleer 2007, Scheers et al. 2020)
<ul>
<li><strong>3130_aom</strong>: subtype aom, subtype oeverkruid (<em>Littorelletea</em>)</li>
<li><strong>3130_na</strong>: subtype na, subtype dwergbiezen (<em>Isoeto-Nanojuncetea</em>)</li>
</ul></li>
<li><strong>3150</strong> - Van nature eutrofe meren met vegetaties van het type <em>Magnopotamion</em> of <em>Hydrocharition</em> (Decleer 2007, Scheers et al. 2020)</li>
<li><strong>3160</strong> - Dystrofe natuurlijke poelen en meren (Decleer 2007, Scheers et al. 2020)</li>
</ul>
<p><strong>Isoëtiden</strong>: laagblijvende rozetbladige planten met stevige, holle, lijn- of priemvormige bladeren bv. knolrus (<em>Juncus bulbosus</em>), oeverkruid (<em>Littorella uniflora</em>), waterlobelia (<em>Lobelia dortmanna</em>), pilvaren (<em>Pilularia globulifera</em>), …</p>
<p><strong>LSVI</strong>: Lokale staat van instandhouding; instrument om lokaal de toestand van een habitattype te evalueren aan de hand van structuur- en vegetatiekenmerken (Oosterlynck et al. 2020).</p>
<p><strong>Steekproefpunt</strong> of <strong>(veld)locatie</strong>: Voor het habitatkwaliteitsmeetnet (zie verder) komt de steekproefeenheid voor stilstaande wateren overeen met de watervlakkencode (Westra et al., 2022). Dit is het niveau waarop de biotische karakterisatie wordt beoogd.</p>
</div>
<div id="doelstelling-en-toepassingsgebied" class="section level2 hasAnchor" number="3.2">
<h2><span class="header-section-number">3.2</span> Doelstelling en toepassingsgebied<a href="#doelstelling-en-toepassingsgebied" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Het doel van het veldprotocol is om gegevens te verzamelen van bepaalde indicatoren die een beoordeling van de LSVI toelaten voor habitattype 2190_a, 3110, 3130_aom, 3130_na, 3140, 3150 en 3160. Deze LSVI-indicatoren zijn beschreven door Oosterlynck et al. (2020).</p>
<p>Het veldprotocol wordt gebruikt voor het bemonsteren van de steekproefpunten van het habitatkwaliteitsmeetnet voor bovengenoemde habitattypen. De selectiemethode van steekproefpunten is beschreven in het rapport over de habitatkwaliteitsmonitoring (Westra et al., 2014; Westra et al., 2022). Dit meetnet is geconcipieerd om de habitatkwaliteit van habitattypen van stilstaande wateren op Vlaams schaalniveau te kunnen inschatten. De resultaten van dit meetnet worden o.a. gebruikt voor de 6-jaarlijkse rapportage over de staat van instandhouding van de habitattypes 31xx en 2190_a aan de Europese Commissie.</p>

</div>
</div>
<div id="beperkingen-van-het-protocol-sec-beperkingen" class="section level1 hasAnchor" number="4">
<h1><span class="header-section-number">4</span> Beperkingen van het protocol {#sec: beperkingen}<a href="#beperkingen-van-het-protocol-sec-beperkingen" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<!--
Alleen in te vullen indien van toepassing.
Bespreek onder welke condities het protocol niet gebruikt kan worden of wanneer afwijkingen nodig zijn ten opzichte van het standaard protocol.
Vermeld hier ook mogelijke interferenties, knelpunten, ...
-->
<p>In sommige omstandigheden kan er geen opname gemaakt worden. De reden hiervoor wordt genoteerd:</p>
<ul>
<li>Tijdelijk ongeschikt (tijdelijk niet toegankelijk door wegenwerken of inrichtingswerken, gevaarlijke hond, drooggevallen, te hoge waterstand, …): het loont in dit geval de moeite om de locatie later in het jaar of tijdens het volgende jaar opnieuw te bezoeken;</li>
<li>Permanent ongeschikt (permanent niet toegankelijk, niet bereikbaar op een veilige manier, geen toestemming voor betreding, …).</li>
</ul>
<p>De vegetatieopnames worden uitgevoerd in het groeiseizoen van de water- en oeverplanten (mei-september). Afhankelijk van het habitattype en de verwachte soorten worden bepaalde opnames bij voorkeur vroeger of later in het groeiseizoen uitgevoerd (Zie Tabel @ref(tab:geschikte_maanden)) . Voor sommige habitattypen is een aanvullend veldbezoek tijdens het voorjaar noodzakelijk om sleutelsoorten te identificeren. Zo bereikt bijvoorbeeld Tolypella intricata, een kenmerkende soort voor habitattype 3140, een optimale groei in april-mei. Ook zijn voor de identificatie van waterranonkels bloeiende exemplaren nodig (mei-juni; habitattype 3130_aom). Indien nodig, kan de soortenlijst tijdens een later veldbezoek (augustus) aangevuld worden met soorten die hun optimum later in het groeiseizoen bereiken. Om de kans op afsterven van watervegetatie te minimaliseren, wordt aanbevolen de vegetatieopnames best voor eind september af te ronden. In eutrofe plassen kan lichtdeprivatie door algenbloei leiden tot vroegtijdig afsterven van watervegetatie, soms al vanaf juni. Daarnaast kunnen sommige wateren in de zomer sterk vertroebelen door intensieve recreatie of vroegtijdig gemaaid worden, waardoor opnames tijdig moeten plaatsvinden.</p>
<p>Klimatologische factoren, zoals langdurige temperatuurextremen, kunnen de tijdelijke aan- of afwezigheid van vegetaties en specifieke indicatorsoorten beïnvloeden.</p>
<table>
<caption>Meest geschikte maanden voor vegetatieopname per habitattype. “x” = geschikt, “(x)” = minder geschikt, “-” = niet aangewezen. {#tab:geschikte_maanden}</caption>
<colgroup>
<col width="15%" />
<col width="10%" />
<col width="7%" />
<col width="9%" />
<col width="9%" />
<col width="15%" />
<col width="17%" />
<col width="14%" />
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>April</th>
<th>Mei</th>
<th>Juni</th>
<th>Juli</th>
<th>Augustus</th>
<th>September</th>
<th>Oktober</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2190_a</td>
<td>-</td>
<td>x</td>
<td>x</td>
<td>x</td>
<td>x</td>
<td>(x)</td>
<td>-</td>
</tr>
<tr class="even">
<td>3110</td>
<td>-</td>
<td>(x)</td>
<td>x</td>
<td>x</td>
<td>x</td>
<td>x</td>
<td>(x)</td>
</tr>
<tr class="odd">
<td>3130_aom</td>
<td>-</td>
<td>x</td>
<td>x</td>
<td>x</td>
<td>x</td>
<td>(x)</td>
<td>-</td>
</tr>
<tr class="even">
<td>3130_na</td>
<td>-</td>
<td>x</td>
<td>x</td>
<td>x</td>
<td>x</td>
<td>x</td>
<td>-</td>
</tr>
<tr class="odd">
<td>3140</td>
<td>(x)</td>
<td>x</td>
<td>x</td>
<td>x</td>
<td>x</td>
<td>(x)</td>
<td>-</td>
</tr>
<tr class="even">
<td>3150</td>
<td>-</td>
<td>x</td>
<td>x</td>
<td>x</td>
<td>x</td>
<td>x</td>
<td>-</td>
</tr>
<tr class="odd">
<td>3160</td>
<td>(x)</td>
<td>x</td>
<td>x</td>
<td>x</td>
<td>x</td>
<td>x</td>
<td>x</td>
</tr>
</tbody>
</table>

</div>
<div id="principe" class="section level1 hasAnchor" number="5">
<h1><span class="header-section-number">5</span> Principe<a href="#principe" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<!--
Korte omschrijving van de principes waarop het protocol gebaseerd is.
Bijvoorbeeld het principe achter het nemen van mengmonsters, principe achter visueel inschatten van de bedekking van een plant, ...
-->
<p>De LSVI geeft inzichten in de kwaliteit van een habitat voor een bepaalde locatie op basis van de vegetatiesamenstelling en structuurkenmerken (Oosterlynck et al. 2020). De LSVI-indicatoren kunnen ingedeeld worden in drie categorieën: vegetatie, verstoring en habitatstructuur. Voor elke indicator wordt een grenswaarde gegeven om een gunstige toestand te onderscheiden van een ongunstige toestand. Via dit veldprotocol worden de nodige gegevens verzameld om alle LSVI-indicatoren van de habitattypen 2190_a en 31xx te kunnen beoordelen. De bepaling of berekening van deze status per LSVI-indicator en het globaal eindoordeel per locatie vormt geen onderdeel van dit protocol. Hierbij kan de LSVI-rekenmodule gebruikt worden (Lommelen et al. 2024).</p>

</div>
<div id="vereiste-competenties" class="section level1 hasAnchor" number="6">
<h1><span class="header-section-number">6</span> Vereiste competenties<a href="#vereiste-competenties" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<!--
Omschrijving van de basiskennis (bv. kennis van bepaalde soorten) en vaardigheden (bv. bepaalde apparatuur kunnen bedienen), die de gebruiker van het protocol moet hebben om het protocol op een gepaste manier te kunnen uitvoeren.
Eventueel kan er verwezen worden naar bepaalde opleidingen.
-->
<p>Er is voldoende kennis van de veldkenmerken van macrofyten die in stilstaande wateren worden aangetroffen vereist. Daarnaast dient men vertrouwd te zijn met technieken om ze te kunnen identificeren. Het gebruik van de Secchi-schijf (protocol <a href="../2023.04/index.html">sfp-113-nl 2023.04</a>) moet bekend zijn.</p>
<p>Daarnaast zijn volgende algemene competenties vereist (naar Bijkerk, 2014):</p>
<ul>
<li>Nauwkeurigheid:de uitvoering van veldmetingen en het vastleggen van veldwaarnemingen vereisen een grote mate van accuraatheid;</li>
<li>Vermogen te plannen en te organiseren: bij de uitvoering van meetprogramma’s moeten tal van werkzaamheden gepland, georganiseerd en op elkaar afgestemd worden. De veldmedewerker moet in staat zijn om hier zelfstandig of in overleg met de projectleider uitvoering aan te geven;</li>
<li>Zelfstandigheid: de veldmedewerker moet in staat zijn om het merendeel van de werkzaamheden zelfstandig (op locatie) uit te voeren;</li>
<li>Vermogen tot samenwerken en communiceren;</li>
<li>De veldmedewerker moet op de hoogte zijn van de na te leven veiligheidsprotocollen die gebonden zijn aan het uitvoeren van taken in, op en rond water. De veldmedewerker moet dan ook fysiek in staat kunnen zijn om dit protocol in veilige omstandigheden te kunnen uitvoeren (kunnen zwemmen, …).</li>
</ul>

</div>
<div id="benodigdheden" class="section level1 hasAnchor" number="7">
<h1><span class="header-section-number">7</span> Benodigdheden<a href="#benodigdheden" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<!--
Opsomming van benodigd materiaal, apparatuur, reagentia,...
-->
<p>Tabel <a href="#tab:Checklist"><strong>??</strong></a> geeft een overzicht van de benodigde apparatuur en materiaal dat tijdens het veldwerk wordt gebruikt; enkele daarvan specifiëren we hieronder.</p>
<table>
<caption>Checklist van benodigde aparatuur en materiaal. {#tab:Checklist}</caption>
<colgroup>
<col width="100%" />
</colgroup>
<tbody>
<tr class="odd">
<td>Veldformulier en handleiding</td>
</tr>
<tr class="even">
<td>Afgeprinte veldkaarten</td>
</tr>
<tr class="odd">
<td>Schrijfgerief: papier en potlood, (alcohol)stift</td>
</tr>
<tr class="even">
<td>Klembord</td>
</tr>
<tr class="odd">
<td>GSM/Smartphone (en/of handcomputer/tablet of gps; zie verder)</td>
</tr>
<tr class="even">
<td>Waterbestendig fototoestel of fototoestel met waterdichte behuizing</td>
</tr>
<tr class="odd">
<td>Lieslaarzen</td>
</tr>
<tr class="even">
<td>Waadpak (zomer-/winterwaadpak)</td>
</tr>
<tr class="odd">
<td>Loep</td>
</tr>
<tr class="even">
<td>Verrekijker</td>
</tr>
<tr class="odd">
<td>Secchi-schijf</td>
</tr>
<tr class="even">
<td>Plooimeter</td>
</tr>
<tr class="odd">
<td>Hersluitbare zakjes</td>
</tr>
<tr class="even">
<td>Waterdichte handschoenen</td>
</tr>
<tr class="odd">
<td>Ontsmettende zeep of handgel</td>
</tr>
<tr class="even">
<td>Vegetatiehark met schaalverdeling</td>
</tr>
<tr class="odd">
<td>Flora van België (Verloove &amp; Van Rossum, 2023) en/of andere determinatiewerken (zie Bijlage 1 @ref(sec: bijlage1))</td>
</tr>
</tbody>
</table>
<div id="apparatuur" class="section level2 hasAnchor" number="7.1">
<h2><span class="header-section-number">7.1</span> Apparatuur<a href="#apparatuur" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<!--
Opsomming van de apparatuur die nodig is en verwijzingen naar de `sip`'s (Standaard Instrument Procedure; `<protocol-code>-YYYY.NN`) indien die er zijn.
Indien geen specifiek `sip`'s voorhanden, illustreer de toegelaten apparatuur met foto's, geef het exacte type apparatuur mee, ...
-->
<div id="binoculaire-stereomicroscoop-enof-lichtmicroscoop" class="section level3 hasAnchor" number="7.1.1">
<h3><span class="header-section-number">7.1.1</span> Binoculaire stereomicroscoop en/of lichtmicroscoop<a href="#binoculaire-stereomicroscoop-enof-lichtmicroscoop" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Planten die tijdens het veldwerk niet geïdentificeerd kunnen worden, kunnen in het labo met een binoculaire stereomicroscoop bekeken worden. Met vergrotingen tot minimaal 80x kunnen detailkenmerken zoals stengelharen, sporenkapsels, etc. bekeken worden. Beschikbaarheid van een tegenlichtbron is hierbij aan te raden. Voor sommige kenmerken kan best een lichtmicroscoop (100x en meer) gebruikt worden (stuifmeelkorrels, structuren op sporenkapsels, etc.).</p>
</div>
<div id="gps" class="section level3 hasAnchor" number="7.1.2">
<h3><span class="header-section-number">7.1.2</span> GPS<a href="#gps" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Voor het navigeren naar het steekproefpunt volstaat een kaart of een gewone gps met een nauwkeurigheid van 3 à 6 m. Een tablet-gps, smartphone-gps of veldcomputer biedt bijgevolg voldoende nauwkeurigheid. Een RTK-gps is niet nodig voor dit type veldwerk, tenzij het een experimentele opzet zou betreffen die een hogere precisie vereist.</p>
</div>
<div id="handcomputer-of-tablet-optioneel" class="section level3 hasAnchor" number="7.1.3">
<h3><span class="header-section-number">7.1.3</span> Handcomputer of tablet (optioneel)<a href="#handcomputer-of-tablet-optioneel" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Voor de positiebepaling of de invoer van veldgegevens op terrein kan gebruik gemaakt worden van een handcomputer of (rugged) tablet. Het toestel zelf of de hoes errond dient geschikt te zijn voor veldomstandigheden (schokbestendig, stofvrij en (spat)waterdicht).</p>
</div>
<div id="sonarapparatuur-bij-bootwerk" class="section level3 hasAnchor" number="7.1.4">
<h3><span class="header-section-number">7.1.4</span> Sonarapparatuur (bij bootwerk)<a href="#sonarapparatuur-bij-bootwerk" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Het gebruik van sonarapparatuur is niet verplicht, maar kan nuttig zijn. Hiermee kan de waterdiepte gepeild worden om de groeidiepte van submerse vegetatie te achterhalen en tevens in ondiepe zones om te voorkomen dat de boot vastloopt of de motor stilvalt door contact met de bodem.</p>
</div>
</div>
<div id="materiaal" class="section level2 hasAnchor" number="7.2">
<h2><span class="header-section-number">7.2</span> Materiaal<a href="#materiaal" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<!--
Opsomming van gebruikte materialen.
Duidelijk aangeven welke materialen toelaatbaar zijn, welke volumes, afmetingen, materiaal, ... 
Vermeld bijvoorbeeld niet staalnamepotje, maar wel: vierkant flesje, volume 250 ml, gegradueerd, vervaardigd uit `PE`, met afsluitbare deksel uit `PP`.
-->
<div id="veldloep" class="section level3 hasAnchor" number="7.2.1">
<h3><span class="header-section-number">7.2.1</span> Veldloep<a href="#veldloep" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Voor de determinatie van planten is een goede loep nodig. De loep moet minstens 10x vergroten. Met een loep van 20x kunnen detailkenmerken (kranswieren, sterrenkroos, etc.) tijdens het veldwerk bekeken worden.</p>
</div>
<div id="vegetatiehark-met-telescopische-steel" class="section level3 hasAnchor" number="7.2.2">
<h3><span class="header-section-number">7.2.2</span> Vegetatiehark met telescopische steel<a href="#vegetatiehark-met-telescopische-steel" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Een hark met telescopische steel maakt het mogelijk om waterplanten op te halen uit het water indien deze niet met de hand te bemonsteren zijn. Hiervoor wordt een hark van ca. 50 cm breed op een tot 3,9 m uitschuifbare steel, bijv. van het merk Gardena, gemonteerd (Figuur <a href="#fig:Figuur1">7.1</a>). Op de hark wordt volièredraad (1 cm brede mazen) bevestigd met ijzerdraad om kleine en fijne waterplanten te kunnen bemonsteren (Figuur @ref(fig: Figuur2)). Op het vaste deel van de steel kan om de 20 cm een merkteken aangebracht worden om de waterdiepte te bepalen.</p>
<div class="figure"><span style="display:block;" id="fig:Figuur1"></span>
<img src="media/Fig1Hark.png" alt="Hark met uitschuifbare steel van het merk Gardena (foto Jo Packet)" width="100%" />
<p class="caption">
Figuur 7.1: Hark met uitschuifbare steel van het merk Gardena (foto Jo Packet)
</p>
</div>
<pre><code>## Error in knitr::include_graphics(&quot;media/Fig2Hark2.jpeg&quot;): Cannot find the file(s): &quot;media/Fig2Hark2.jpeg&quot;</code></pre>
</div>
<div id="dubbelzijdige-dreghark" class="section level3 hasAnchor" number="7.2.3">
<h3><span class="header-section-number">7.2.3</span> Dubbelzijdige dreghark<a href="#dubbelzijdige-dreghark" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Bij inventarisatie van de vegetatie in diepere zones met een boot, wordt een dreghark gebruikt (Figuur @ref(fig: Figuur3)). Deze bestaat uit een dubbelzijdige, metalen hark met gekromde tanden, die bedekt is met volièredraad. Deze worden met de rugzijden aan elkaar bevestigd. De dreghark is voorzien van korte steel, bevestigd aan een lange, stevige nylonkoord van een 25-tal meter lang. Om de dreghark te gebruiken wordt deze vanuit de boot in het water geworpen zoals een werpanker en over een afstand van ongeveer 10 meter over de bodem getrokken. Het is belangrijk om de hark direct en in één vloeiende beweging omhoog te halen, zonder pauzes, zodat de verzamelde vegetatie erop blijft liggen.</p>
<pre><code>## Error in knitr::include_graphics(&quot;media/Fig3Hark3.jpeg&quot;): Cannot find the file(s): &quot;media/Fig3Hark3.jpeg&quot;</code></pre>
</div>
<div id="hersluitbare-zakjes-en-alcoholstift" class="section level3 hasAnchor" number="7.2.4">
<h3><span class="header-section-number">7.2.4</span> Hersluitbare zakjes en (alcohol)stift<a href="#hersluitbare-zakjes-en-alcoholstift" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Als identificatie in het veld niet mogelijk is, wordt het plantenmateriaal naar het labo gebracht voor verdere determinatie. Voor het tijdelijk bewaren van plantenmateriaal worden hersluitbare zakjes gebruikt. Deze worden gelabeld met een (alcohol)stift (veldcode en datum) en/of voorzien van een papieren label met dezelfde informatie in potlood, dat in het zakje wordt bijgevoegd.</p>
</div>
<div id="secchi-schijf" class="section level3 hasAnchor" number="7.2.5">
<h3><span class="header-section-number">7.2.5</span> Secchi-schijf<a href="#secchi-schijf" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Een secchi-schijf met een diameter van 20 cm (Figuur @ref(fig: Figuur4)) wordt gebruikt om de secchi-diepte te bepalen. Het koord waaraan de secchi-schijf is bevestigd, is voorzien van een maatverdeling om de diepte te kunnen bepalen. Indien een secchi-schijf met andere diameter wordt gebruikt, dient dit vermeld te worden.</p>
<pre><code>## Error in knitr::include_graphics(&quot;media/Fig4Secchi.jpeg&quot;): Cannot find the file(s): &quot;media/Fig4Secchi.jpeg&quot;</code></pre>
</div>
<div id="plooimeter" class="section level3 hasAnchor" number="7.2.6">
<h3><span class="header-section-number">7.2.6</span> Plooimeter<a href="#plooimeter" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Een vouwmeter van minimaal 2 meter voor de dieptebepaling.</p>
</div>
<div id="determinatiewerken" class="section level3 hasAnchor" number="7.2.7">
<h3><span class="header-section-number">7.2.7</span> Determinatiewerken<a href="#determinatiewerken" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Relevante determinatiewerken worden in Bijlage 1 <a href="#sec:bijlage1"><strong>??</strong></a> opgesomd.</p>
</div>
<div id="boot" class="section level3 hasAnchor" number="7.2.8">
<h3><span class="header-section-number">7.2.8</span> Boot<a href="#boot" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Een boot wordt enkel gebruikt bij diepere plassen op meer dan 3 à 4 m diepte. Bij grote, diepe plassen wordt een boot met motor gebruikt omdat het slepen van een werphark over de waterbodem anders niet praktisch haalbaar is. De afmetingen van de boot zijn bij voorkeur minstens 4 m lengte op 2,00 m breedte. Bij deze afmetingen is er voldoende ruimte om het nodige materiaal te stockeren tijdens het bootwerk. Ook moet de boot voldoende stabiliteit bieden om rechtstaand met de dreghark te kunnen werken. In sommige gevallen kan een kleinere boot met elektromotor worden gebruikt. Dit type boot kan handig zijn om grote ondiepere watersystemen met variabele diepte te bemonsteren of indien rekening gehouden moet worden met verstoringsgevoelige fauna of bijzondere kwaliteitseisen (bv. drinkwaterproductie).</p>
</div>
</div>
<div id="reagentia-en-oplossingen-indien-van-toepassing" class="section level2 hasAnchor" number="7.3">
<h2><span class="header-section-number">7.3</span> Reagentia en oplossingen (indien van toepassing)<a href="#reagentia-en-oplossingen-indien-van-toepassing" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Niet van toepassing</p>
<!--
Een opsomming van reagentia, welke zuiverheid, volume, veiligheidsvoorschriften.
Bijvoorbeeld. Zwavelzuur (`H2SO4`), geconcentreerd (96%), pro analyse en veiligheidsinfo (sterk zuur, bijtend, gebruik handschoenen, bril en masker bij gebruik)
Een opsomming van oplossingen, welke zuiverheid, volume, veiligheidsvoorschriften.
Indien deze oplossingen zelf worden bereid, vermeld dan ook de bereidingswijze.
bijvoorbeeld: Zwavelzuur `1M`: verdun zwavelzuur geconcentreerd 18 maal met `ultrapuur` water.
Opgelet: giet altijd zwavelzuur bij water en nooit omgekeerd!
-->

</div>
</div>
<div id="werkwijze" class="section level1 hasAnchor" number="8">
<h1><span class="header-section-number">8</span> Werkwijze<a href="#werkwijze" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="uitvoering" class="section level2 hasAnchor" number="8.1">
<h2><span class="header-section-number">8.1</span> Uitvoering<a href="#uitvoering" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<!--
Gedetailleerde omschrijving van alle stappen die doorlopen moeten worden om het protocol uit te voeren.
Subtitels gebruiken om elke stap te omschrijven.
-->
<div id="voorafgaand-aan-het-terreinwerk" class="section level3 hasAnchor" number="8.1.1">
<h3><span class="header-section-number">8.1.1</span> Voorafgaand aan het terreinwerk<a href="#voorafgaand-aan-het-terreinwerk" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Volgende taken dienen voorafgaand aan het veldbezoek uitgevoerd te
worden:</p>
<ul>
<li><p>Afdruk van veldkaarten met gepast schaalniveau en de recentst
beschikbare orthofoto, bij voorkeur op A3 formaat.</p></li>
<li><p>Afdruk van veldformulieren van de verschillende habiattypen
(dubbelzijdig)</p></li>
<li><p>Offline zetten van eventuele kaarten/applicaties op
handcomputer/tablet voor het geval mobiele data niet beschikbaar is
in het veld</p></li>
<li><p>Eigenaar/beheerder contacteren</p></li>
<li><p>Adres of routebeschrijving van locatie opzoeken</p></li>
<li><p>Inschatten of een (belly)boot nodig is voor het uitvoeren van de
vegetatieopname</p></li>
</ul>
</div>
<div id="lokaliseren-en-documenteren-van-veldlocatie" class="section level3 hasAnchor" number="8.1.2">
<h3><span class="header-section-number">8.1.2</span> Lokaliseren en documenteren van veldlocatie<a href="#lokaliseren-en-documenteren-van-veldlocatie" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Navigeer met een gps naar de oever van de veldlocatie.</p>
<p>Indien het steekproefpunt tijdelijk of permanent ongeschikt is (zie
@ref(sec: beperkingen)), wordt dit samen met de reden genoteerd op het
veldformulier. Bij een permanent ongeschikt meetpunt wordt dit vervangen
door het eerstvolgende reservepunt. Bij tijdelijke ongeschiktheid wordt
de locatie later in het jaar of het daaropvolgende jaar opnieuw bezocht.
Ook opmerkingen in verband met betreding en toegang worden genoteerd.</p>
<p>Alvorens het water betreden wordt, wordt ingeschat wat de geschikte
kledij is voor de opname. Bij ondiepe plassen kan er gekozen worden voor
lieslaarzen of een waadpak. Bij diepe plassen zal het gebruik van een
boot noodzakelijk zijn. Wanneer er met een boot gewerkt wordt, dienen
minstens 3 personen aanwezig te zijn: 2 in de boot voor de opname en
iemand op de oever. Men dient zich aan de veiligheidsvoorschriften te
houden.</p>
</div>
<div id="bepaling-aanwezige-habitattypen" class="section level3 hasAnchor" number="8.1.3">
<h3><span class="header-section-number">8.1.3</span> Bepaling aanwezige habitattypen<a href="#bepaling-aanwezige-habitattypen" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Bepaal eerst of het geselecteerde habitattype aanwezig is volgens de
praktische handleiding voor het typeren van de stilstaande wateren in
Vlaanderen (Scheers et al. 2016) en de beschrijving van habitattype
2190_a (Denys et al. 2021). Voor alle habitat(sub)typen die aanwezig
zijn in de plas wordt een afzonderlijk veldformulier ingevuld.</p>
<p><strong>Oppervlakteaandeel van habitat in plas</strong>: Mits er meerdere typen
aanwezig zijn in een waterlichaam, dan wordt er getracht een
representatieve verdeling aan de types binnen de plas te geven. De som
van de verdeling moet steeds 100% zijn.</p>
<p>Ook de reden van afwezigheid van het habitattype wordt opgegeven, m.n.
waarom voldoet de locatie niet aan de definitie van het habitattype:</p>
<ul>
<li><p>Te weinig open water aanwezig (gedomineerd door helofytenvegetaties,
dus behorend tot een moerastype),</p></li>
<li><p>Gracht</p></li>
<li><p>De plas is gedempt</p></li>
<li><p>Er zijn geen soorten aanwezig die typisch zijn voor het habitattype</p></li>
<li><p>…</p></li>
</ul>
</div>
<div id="vegetatieopname-sec-vegetatieopname" class="section level3 hasAnchor" number="8.1.4">
<h3><span class="header-section-number">8.1.4</span> Vegetatieopname {#sec: vegetatieopname}<a href="#vegetatieopname-sec-vegetatieopname" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>De waterdiepte bepaald de wijze van opname:</p>
<ul>
<li><p>Indien de waterdiepte dit toelaat, wordt de opname al wadend
uitgevoerd</p></li>
<li><p>Indien het centrale deel van de plas ondoorwaadbaar is, maar de zone
nabij de oever wel doorwaadbaar is, wordt het diepere deel harkend
vanuit de doorwaadbare zone bemonsterd.</p></li>
<li><p>In diepe, grotere wateren wordt met behulp van een kleine boot
geïnventariseerd.</p></li>
</ul>
<p>Vertrek vanop de oever van de locatie, waad langsheen de oever om de
vegetatieopname te maken. Dit kan in wijzerszin of tegenwijzerzin
gebeuren, afhankelijk van de stand van de zon. Waden met de zon in de
rug is optimaal, omdat dit de zichtbaarheid van de submerse vegetatie
vergroot en de reflectie beperkt. Bij ondiepe plassen wordt
zig-zag-gewijs van de oever naar het centrale deel van de plas gewaad om
een beeld te krijgen van de volledige plas. Afhankelijk van de grootte
van de plas, de diversiteit aan soorten en de vegetatiedichtheid zal het
zigzag-patroon meer of minder dens zijn.</p>
<p>Bij diepe, vegetatierijke plassen wordt het centrale deel met een boot
geïnventariseerd, waarbij de vegetatie door middel van een dreghark
wordt opgehaald. Eerst wordt de kolonisatiediepte bepaald, dit is de
maximale diepte waar er vegetatiegroei wordt waargenomen. Daarna wordt
de vegetatiezone in transecten gevaren, waarbij op verschillende dieptes
de vegetatie met een dreghark wordt bemonsterd. Het diepe onbegroeide
deel wordt tenslotte sporadisch bemonsterd om te checken op vegetatie.</p>
<p>De vegetatieopname wordt beperkt tot het waterdeel en de oeverzone die
frequent onder water komt te staan. Bij plassen met een zeer geleidelijk
talud, bijvoorbeeld bij habitattype 3160, kan de overgang van de
oeverzone soms breed zijn; hier wordt echter de directe oeverzone
inbegrepen in de opname. Bij twijfel wordt de screening beperkt tot de
contour van watervlakken; deze toont de begrenzing door de
winterwaterstand. De meer afgelegen oeverzone kan in dit geval deel
uitmaken van een ander habitattype (hoogveen/natte heide) en aldus
volgens een ander protocol worden beoordeeld.</p>
<p><strong>Bedekking individuele soorten</strong> Eerst wordt een lijst van de aanwezige
sleutel- en indicatorsoorten opgesteld (Zie veldformulieren @ref(sec:
bijlage); Bijlage 2 t.e.m. 8 en Oosterlynck et al. 2020). Na de
volledige plas te hebben gescreend, worden de bedekkingen genoteerd met
de bedekkingsschaal van Tabel @ref(tab: bedekkingsschaal).</p>
<table>
<caption>Bedekkingsschaal Tansley-Meren (Schneiders et al., 20040
{#tab:bedekkingsschaal}</caption>
<colgroup>
<col width="33%" />
<col width="33%" />
<col width="33%" />
</colgroup>
<thead>
<tr class="header">
<th>Code</th>
<th>Tansley</th>
<th>Beschrijving</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>r</strong></td>
<td>zeldzaam</td>
<td>&lt; 3 exemplaren</td>
</tr>
<tr class="even">
<td><strong>o</strong></td>
<td>occasioneel</td>
<td>&gt; of = 3 exemplaren, &lt; 5% bedekkend</td>
</tr>
<tr class="odd">
<td><strong>f</strong></td>
<td>frequent</td>
<td>bedekkend (ca. 5 %), oplopend tot 15-20% of &gt; 100 exemplaren</td>
</tr>
<tr class="even">
<td><strong>a</strong></td>
<td>abundant</td>
<td>bedekking 15 (20) &lt; x &lt; 40%</td>
</tr>
<tr class="odd">
<td><strong>cd</strong></td>
<td>co-dominant</td>
<td>bedekking &gt; 40% van meerdere soorten</td>
</tr>
<tr class="even">
<td><strong>d</strong></td>
<td>dominant</td>
<td>bedekking &gt; 40% van 1 soort</td>
</tr>
</tbody>
</table>
<p>Indien identificatie op het terrein niet mogelijk is, verificatie door
een specialist nodig is, of het een zeer zeldzame vondst betreft, worden
(delen van) planten meegenomen in een hersluitbaar plastic zakje, licht
bevochtigd en voorzien van de locatiecode om deze later in het labo te
kunnen determineren. Het volgnummer van het herbariumspecimen wordt
genoteerd op het veldformulier. Het specimen wordt best uit de zon, en
zo koel mogelijk gehouden na verzamelen en tijdens transport. Achteraf
kan dit nog enkele dagen in de koelkast worden bewaard alvorens
gedetermineerd of gefixeerd te worden.</p>
</div>
<div id="bedekking-van-groepen-van-soorten" class="section level3 hasAnchor" number="8.1.5">
<h3><span class="header-section-number">8.1.5</span> Bedekking van groepen van soorten<a href="#bedekking-van-groepen-van-soorten" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><strong>Sleutelsoorten</strong>: de bedekking van sleutelsoorten per habitattype
wordt individueel ingeschat volgens de Tansley-schaal (Tabel @ref(tab:
bedekkingsschaal)). De totale bedekking (%) van alle sleutelsoorten
samen wordt eveneens genoteerd. Voor habitattype 2190_a worden
sleutelsoorten onderverdeeld in hydrofyten en niet-hydrofyten. Voor
habitattype 3140 wordt aangegeven of de kranswiervelden bestaan uit meer
of minder dan de helft uit sleutelsoorten (op basis van bedekking).</p>
<p>Bedekking <strong>verstoringsindicatoren</strong>: Het percentage
verstoringsindicatoren (eutrofiëringsindicatoren, verzuring en invasieve
exoten) wordt ingeschat als oppervlakte-percentage, oftewel de projectie
t.o.v. het volledige wateroppervlak. Voor habitattype 2190_a wordt de
kroosbedekking (%) genoteerd als eutrofiëringsindicator.</p>
<p>Indien verschillende habitattypen en/of subtypen voorkomen, wordt voor
elk van de typen de verstoringspercentages op plasniveau ingeschat. Voor
bijvoorbeeld de gezamenlijke aanwezigheid van 3130_na als 3130_aom in
een plas, worden eutrofiëringspercentages voor beide subtypes op de
volledige plas ingeschat.</p>
<p>Voor habitattype 2190_a wordt het percentage van verschillende
<strong>vegetatielagen</strong> ingeschat:</p>
<ul>
<li><p>(bodemwortelende) <strong>Submerse vegetatie</strong>: procentuele oppervlakte
van de plas bedekt met ondergedoken en wortelende vegetatie; dit is
inclusief <em>Ceratophyllum</em> en exclusief <em>Utricularia</em>.</p></li>
<li><p><strong>Kranswieren</strong>: oppervlakte van de plas bedekt met Characeae.
Opgelet, deze zijn ook vervat in het percentage submerse vegetatie,
dus het percentage submerse vegetatie is steeds groter dan of gelijk
aan het percentage kranswieren.</p></li>
<li><p><strong>Overhangende bomen en struiken</strong>: dit is de som van de
oppervlakten van het wateroppervlak en de langdurig geïnundeerde
oever dat beschaduwd wordt door overhangende bomen/struiken, dus
deze die zich niet in de plas bevinden. Bij het bepalen van de
beschaduwing wordt een verticale projectie van de overhangende
boom/struiken gebruikt. Dit geeft een indicatie van slechte
lichtomstandigheden in het water, en daardoor vegetatiegroei
belemmert.</p></li>
<li><p><strong>Bomen en struiken</strong>: percentage bedekking van het wateroppervlak
en de langdurig geïnundeerde oever met bomen of struiken; enkel deze
die zich in de plas bevinden of die in de geïnundeerde oever
wortelen. Dit is een indicatie van successie.</p></li>
</ul>
</div>
<div id="structuurkenmerken" class="section level3 hasAnchor" number="8.1.6">
<h3><span class="header-section-number">8.1.6</span> Structuurkenmerken<a href="#structuurkenmerken" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="vertical-structuur" class="section level4 hasAnchor" number="8.1.6.1">
<h4><span class="header-section-number">8.1.6.1</span> Vertical structuur<a href="#vertical-structuur" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>De verticale structuur brengt de successie in rekening. Een overmatige
aanwezigheid van hoger groeiende, meer concurrentiekrachtige planten
bemoeilijkt de groei van de kenmerkende isoëtiden en dwergbiezen:</p>
<ul>
<li><p><strong>Isoëtiden</strong>: Voor HT3110 wordt de bedekking van isoëtiden versus
andere groeivormen genoteerd, oftewel door een Tansley-inschatting
per groep te noteren of door aan te kruisen of het aandeel isoëtiden
groter of kleiner is dan de andere groeivormen.</p></li>
<li><p><strong>‘Opgaande’ soorten</strong>: voor habitattype 3130_na wordt de
overgroeiing van de vegetatievlekken (definitie: zie verder) door
hoger groeiende niet-sleutelsoorten ingeschat. Dit is de vegetatie
hoger dan 15 cm en kan naast helofyten ook bestaan uit submerse
vegetatie die zorgt voor concurrentie.</p></li>
</ul>
<p>Een overdadige ontwikkeling van <strong>helofyten</strong> zorgt voor concurrentie
voor licht en ruimte, waardoor de groei van ondergedoken en drijvende
vegetatie wordt bemoeilijkt.</p>
<p>De bedekking van helofyten (exclusief sleutelsoorten) wordt als
percentage ingeschat bij habitattype 3130_aom, 3140 en 3150; hierbij
wordt dit percentage ingeschat op plasniveau; m.n. % bedekking ten
opzichte van het wateroppervlak. Ook bij habitattype 2190_a komt dit aan
bod als de bedekking van <strong>robuuste monocotylen</strong>.</p>
</div>
<div id="horizontale-structuur" class="section level4 hasAnchor" number="8.1.6.2">
<h4><span class="header-section-number">8.1.6.2</span> Horizontale structuur<a href="#horizontale-structuur" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Bij de horizontale structuur wordt beoordeeld of de typische vegetaties
voldoende groot zijn, de zogenaamde <strong>vegetatievlekken</strong> die
voornamelijk bestaan uit sleutelsoorten. De omschrijving van de term
vegetatievlek verschilt per habitattype:</p>
<ul>
<li><p>3110: &gt; of = 4 exemplaren van sleutelsoorten per m² of 4 exemplaren
staan op maximum 0,5 m van elkaar;</p></li>
<li><p>3130_aom en 3130_na: ijle tot dichte vegetaties waarin
sleutelsoorten meer bedekken dan andere soorten;</p></li>
<li><p>3140: kranswiervelden of dichte vegetaties, voor meer dan ¾
bestaande uit kranswieren (zowel sleutelssoorten als overige
kranswieren);</p></li>
<li><p>3150: vegetaties waarin sleutelsoorten meer bedekken dan andere
soorten.</p></li>
</ul>
<p>Tijdens het waden wordt de grootte van deze vegetatievlekken ingeschat.
Er wordt van twee vegetatievlekken gesproken indien de afstand tussen
beide minstens 2 meter bedraagt. Er is geen minimum-oppervlakte om van
een vegetatievlek te kunnen spreken. Wanneer de sleutelsoorten zeer
schaars aanwezig zijn en er slechts enkele exemplaren worden
aangetroffen, wordt dit als een vegetatievlek van de laagste
grootteklasse gerekend.</p>
<p>De oppervlakteklasse van de grootste aaneengesloten vegetatievlek wordt
aangekruist op het veldformulier.</p>
<p>Bij de doorgaans schaarse vegetaties van habitattype 3160 wordt dit
criterium beoordeeld door de ruimtelijke samenhang met het hydrologisch
samenhangende successiestadium ‘oligotroof en zuur overgangsveen’
(<strong>habitattype 7140_ oli</strong>) te beoordelen. De aan- of afwezigheid van
de aanpalende habitatvlekken van het habitattype 7140_oli wordt
aangekruist op het veldformulier. Voor een beschrijving van dit
habitattype wordt verwezen naar Decleer (2007).</p>
</div>
</div>
<div id="algemene-standplaatskenmerken" class="section level3 hasAnchor" number="8.1.7">
<h3><span class="header-section-number">8.1.7</span> Algemene standplaatskenmerken<a href="#algemene-standplaatskenmerken" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="waterpeil" class="section level4 hasAnchor" number="8.1.7.1">
<h4><span class="header-section-number">8.1.7.1</span> Waterpeil<a href="#waterpeil" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p><strong>Waterpeil</strong>: Een afwijkend waterpeil wordt genoteerd. Bij een
uitzonderlijk hoog waterpeil wordt afgeraden om een vegetatieopname te
maken, enerzijds omwille van veiligheid en anderzijds vanwege het
beperkt doorzicht dat meestal gepaard gaat met een uitzonderlijk hoog
waterpeil.</p>
<p><strong>Schommeling winter/zomer</strong>: de schommeling tussen winter- en
zomerwaterpeil wordt ingeschat door de vegetatie en structuurkenmerken
van de oeverzone net boven het waterpeil te beoordelen. De
vegetatieopname vindt plaats tijdens het seizoen wanneer het waterpeil
doorgaans het laagst staat. Aan de oeverzijde kan ingeschat worden
hoeveel hoger het winterpeil is.</p>
<p><strong>Permanentie</strong>: Voor habitattype 2190_a wordt aangekruist of de plas
permanent water bevat of niet. Er wordt een onderscheid gemaakt tussen:
permanent waterhoudend (nooit droogvallend), semi-permanent (soms
droogvallend) of periodiek droogvallend (jaarlijks droogvallend).</p>
</div>
<div id="maximale-diepte" class="section level4 hasAnchor" number="8.1.7.2">
<h4><span class="header-section-number">8.1.7.2</span> Maximale diepte<a href="#maximale-diepte" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>De maximale diepte wordt bepaald door middel van een plooimeter, de
sonar of de lengteaanduiding op het koord van de dreghark. De
diepteklasse van deze maximale diepte wordt vervolgens aangekruist op
het veldformulier.</p>
</div>
<div id="helderheid-van-de-waterkolom" class="section level4 hasAnchor" number="8.1.7.3">
<h4><span class="header-section-number">8.1.7.3</span> Helderheid van de waterkolom<a href="#helderheid-van-de-waterkolom" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Indien er geen bodemzicht is, wordt de secchi-diepte bepaald. De schijf
wordt langzaam in het water gelaten en de diepte waarop het onderscheid
tussen de witte en de zwarte vlakken niet meer zichtbaar is, wordt
afgelezen van de maatverdeling op het touw. Dit wordt enkele malen
herhaald. Indien de schijf tot op de bodem zichtbaar is, wordt de
waterdiepte van de meetplaats genoteerd als secchi-diepte. De meting van
de secchi-diepte dient - indien mogelijk - op het diepste punt van de
plas uitgevoerd te worden. Zie ook protocol <a href="../2023.04/index.html">sfp-113-nl
2023.04</a>.</p>
</div>
<div id="bodemsubstraat" class="section level4 hasAnchor" number="8.1.7.4">
<h4><span class="header-section-number">8.1.7.4</span> Bodemsubstraat<a href="#bodemsubstraat" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Voor 2190_a wordt het bodemsubstraat genoteerd: zand, klei, veraard
veen, puin of overig substraat. Indien meerdere typen substraat
voorkomen, wordt dit ingeschat d.m.v. percentages.</p>
</div>
</div>
</div>
<div id="registratie-en-bewaring-van-resultaten" class="section level2 hasAnchor" number="8.2">
<h2><span class="header-section-number">8.2</span> Registratie en bewaring van resultaten<a href="#registratie-en-bewaring-van-resultaten" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="invoer-veldgegevens" class="section level3 hasAnchor" number="8.2.1">
<h3><span class="header-section-number">8.2.1</span> Invoer veldgegevens<a href="#invoer-veldgegevens" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>De invoer van veldgegevens gebeurt digitaal op het terrein met een
(rugged) tablet in INBOVEG (Survey = HT31xx_LSVI_StilstaandeWateren) of
analoog op een veldformulier (@ref(sec: bijlage); Bijlage 2 t.e.m. 8).</p>
</div>
<div id="determinaties" class="section level3 hasAnchor" number="8.2.2">
<h3><span class="header-section-number">8.2.2</span> Determinaties<a href="#determinaties" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Soorten die in het veld niet op naam gebracht kunnen worden, kunnen tot
hooguit één week gekoeld bewaard worden. Ze kunnen in het labo op naam
gebracht worden met een loep, stereomicroscoop of lichtmicroscoop en
relevante determinatiewerken (Bijlage @ref(sec: bijlage1)). Indien relevant, kunnen
foto’s genomen worden. De geïdentificeerde specimen worden bewaard in
een herbarium.</p>
</div>
<div id="opslag-van-fotos" class="section level3 hasAnchor" number="8.2.3">
<h3><span class="header-section-number">8.2.3</span> Opslag van foto’s<a href="#opslag-van-fotos" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>De foto’s worden chronologisch per datum in mappen bewaard, waarbij de
locatiecode en de datum in de map- of bestandsnaam worden vermeld.</p>

</div>
</div>
</div>
<div id="kwaliteitszorg" class="section level1 hasAnchor" number="9">
<h1><span class="header-section-number">9</span> Kwaliteitszorg<a href="#kwaliteitszorg" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<!--
Vermeld alle acties bij het uitvoeren van het protocol om tot kwaliteitsvolle resultaten te komen.
Daarnaast kan ook een checklist toegevoegd worden om na te gaan of alle stappen van het veldprotocol op een correcte manier doorlopen zijn (bv. Zijn alle velden in veldformulier ingevuld, zijn alle stalen gelabeld, ...).
Indien er niet aan bepaalde kwaliteitscriteria voldaan wordt, kan er eventueel verwezen worden naar corrigerende maatregelen.
In dit onderdeel kunnen ook bepaalde interkalibratie-oefeningen vermeld worden, die bijvoorbeeld voorafgaand aan elk veldseizoen worden uitgevoerd door de gebruikers van het protocol. 
-->
<ul>
<li><p>De checklist van het veldmateriaal staat in Tabel <a href="#tab:Checklist"><strong>??</strong></a>. Dit materiaal is in goede staat en wordt meegenomen bij de uitvoering van het veldwerk.</p></li>
<li><p>Het veldformulier wordt volledig ingevuld. Net na de inventarisatie wordt gecontroleerd of alle velden van het veldformulier zijn ingevuld.</p></li>
<li><p>In INBOVEG zijn een aantal automatische controles ingebouwd of verplicht in te vullen velden aangeduid, waardoor de kans op foutief ingevoerde waarden wordt verminderd.</p></li>
<li><p>Specimen die op het terrein niet op naam kunnen worden gebracht, worden meegenomen naar het labo ter identificatie. Bij twijfel wordt dit specimen voorgelegd aan derden ter controle.</p></li>
<li><p>Voor elke in INBOVEG ingevoerde opname wordt gecontroleerd of het aantal en de bedekking van de ingevoerde soorten overeenkomt met deze van het veldformulier. Nadat alle opnames van een veldseizoen zijn ingevoerd in INBOVEG, wordt via query’s of kruistabellen gecontroleerd of alle kenmerken voor alle opnames werden ingevoerd in INBOVEG.</p></li>
</ul>

</div>
<div id="veiligheid" class="section level1 hasAnchor" number="10">
<h1><span class="header-section-number">10</span> Veiligheid<a href="#veiligheid" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<!--
Alle aandachtspunten in verband met veilig werken.
-->
<ul>
<li><p>Voor opnames in ondiepe wateren (waterdiepte &lt; 1 m) kan alleen op terrein worden gegaan; bij diepere wateren (&gt; 2 m) wordt steeds met 2 personen op het terrein gegaan. Voor wateren met een diepte tussen 1 en 2 m hangt het van de veldomstandigheden af of het veldwerk alleen kan uitgevoerd worden of niet.</p></li>
<li><p>Neem steeds een hark of stevige stok mee bij het waden. Je kan er de waterdiepte mee peilen voor je in het water gaat; je kan deze gebruiken om je evenwicht te behouden of als hulpstuk gebruiken om uit het water te geraken bij steile oevers.</p></li>
<li><p>De veldmedewerker beschikt steeds over een GSM en een lijst van nuttige telefoonnummers.</p></li>
<li><p>Tijdens een opname in verontreinigd water draagt men waterdichte handschoenen; na de opname wast men de handen met ontsmettende zeep om het risico op besmetting te beperken.</p></li>
<li><p>Voorzichtigheid is ten zeerste geboden bij diepe wateren, bij weke waterbodem en bij gladde of zeer steile taluds. In deze omstandigheden kan een alternatieve opnametechniek toegepast (zie @ref(sec: vegetatieopname) vegetatieopname – waterdiepte bepaalt de wijze van opname). Gebruik een reddingstouw of reddingsvest wanneer de situatie dit vereist.</p></li>
<li><p>Bij bootwerk wordt er minstens met twee personen geïnventariseerd die voldoende ervaring hebben om de boot en uitrusting te bedienen. De boot, reddingsvesten en roeispanen zijn in goede staat en indien nodig gekeurd volgens de vereiste voorschriften. Bij uitval van de motor of in geval van nood kan de boot bediend worden door roeispanen (min. 2 stuks).</p></li>
</ul>
<p>Tijdens het veldwerk gelden volgende aanvullende veiligheidsregels:</p>
<ul>
<li><p>Algemene veiligheidsregels rond het werken in en nabij water (protocol in ontwikkeling sfp-112).</p></li>
<li><p>Bioveiligheidsmaatregelen voor het voorkomen van de verspreiding van invasieve exoten (protocol in ontwikkeling sfp-015).</p></li>
</ul>

</div>
<div id="samenvatting" class="section level1 hasAnchor" number="11">
<h1><span class="header-section-number">11</span> Samenvatting<a href="#samenvatting" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<!--
Een samenvattende opsomming van de te volgen stappen.
Gebruik eventueel een stroomschema indien dit het protocol kan verduidelijken.
-->
<ul>
<li><p>STAP 1. Voer de taken voorafgaand aan het veldbezoek uit en <strong>controleer de lijst met benodigdheden</strong> voor vertrek.</p></li>
<li><p>STAP 2. <strong>Navigeer met GPS naar de locatie</strong>. Bepaal of de locatie geschikt is voor een vegetatie-opname. Is de locatie toegankelijk? Is het habitattype aanwezig (niet steeds op het eerste zicht te bepalen). Indien de plas ontoegankelijk is of geen habitat blijkt te bevatten wordt dit gedocumenteerd en wordt er geen opname gemaakt.</p></li>
<li><p>STAP 3. <strong>Voer de vegetatieopname uit</strong>. Afhankelijk van de waterdiepte gebeurt dit op één van volgende manieren: door het water wadend, harkend vanuit het doorwaadbare deel, harkend vanaf de oever of met boot. Ook de <strong>standplaatskenmerken worden genoteerd</strong> op het veldformulier.</p></li>
<li><p>STAP 4. Soorten die niet konden worden geïdentificeerd op terrein, worden binnen de week na bemonstering gedetermineerd. Gegevens worden ingegeven in INBOVEG indien dit nog niet is gebeurd op terrein.</p></li>
</ul>

</div>
<div id="referenties" class="section level1 unnumbered hasAnchor">
<h1>Referenties<a href="#referenties" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="refs">

</div>
<ul>
<li><p>Bijkerk R. (2014). Handboek hydrobiologie. Deel 1. Biologisch onderzoek voor de ecologische beoordeling van Nederlandse zoete en brakke oppervlaktewateren. Stichting Toegepast Onderzoek Waterbeheer, Amersfoort.</p></li>
<li><p>Decleer K. (2007). Europees beschermde natuur in Vlaanderen en het Belgisch deel van de Noordzee : habitattypen : dier- en plantensoorten. <em>Mededelingen van het Instituut voor Natuur- en Bosonderzoek</em> 2007(1). Instituut voor Natuur- en Bosonderzoek, Brussel.</p></li>
<li><p>Denys L., Packet J., Provoost S. (2021). De vegetatie van duinwateren aan de Vlaamse kust. Kenmerken, beheer en lokale staat van instandhouding. <em>Rapporten van het Instituut voor Natuur- en Bosonderzoek</em> 2021 (39). Instituut voor Natuur- en Bosonderzoek, Brussel.</p></li>
<li><p>Denys L. (2011). Advies over de bepaling van de vegetatieontwikkeling van submerse vegetatie en enkele aanpassingen m.b.t. de beoordeling van macrofyten in Vlaamse meren voor de Europese Kaderrichtlijn Water. <em>Adviezen van het Instituut voor Natuur- en Bosonderzoek</em> 2011 <em>(</em>109). Instituut voor Natuur- en Bosonderzoek, Brussel.</p></li>
<li><p>Lommelen E., Oosterlynck P., Van Spaendonk G., Van Calster H., Van Hove M., Westra T. (2024). LSVI: Rekenmodule Lokale Staat Van Instandhouding van habitattypen. R package version 0.1.3, <a href="https://github.com/inbo/LSVI" class="uri">https://github.com/inbo/LSVI</a>.</p></li>
<li><p>Scheers K., Packet J., Denys L., Smekens V., De Saeger S. (2016). BWK en Habitatkartering, een praktische handleiding. Deel 3 : veldsleutel voor het typeren van stilstaande wateren in Vlaanderen. <em>Rapporten van het Instituut voor Natuur- en Bosonderzoek</em> 2016 (11613720)<em>.</em> Instituut voor Natuur- en Bosonderzoek, Brussel.</p></li>
<li><p>Schneiders A., Denys L., Jochems H., Vanhecke L., Triest L., Es K., Packet J., Knuysen K., Meire P. (2004). Ontwikkelen van een monitoringsysteem en een beoordelingssysteem voor macrofyten in oppervlaktewateren in Vlaanderen overeenkomstig de Europese Kaderrichtlijn Water. <em>Rapporten van het Instituut voor Natuurbehoud</em> 2004 (1). Instituut voor Natuurbehoud, Brussel.</p></li>
<li><p>Oosterlynck P., De Saeger S., Leyssen A., Provoost S., Thomaes A., Vandevoorde B., Wouters J., &amp; Paelinckx D. (2020). Criteria voor de beoordeling van de lokale staat van instandhouding van de Natura2000 habitattypen in Vlaanderen. <em>Rapporten van het Instituut voor Natuur- en Bosonderzoek</em> 2020 (27). Instituut voor Natuur- en Bosonderzoek, Brussel. DOI: <a href="doi.org/10.21436/inbor.14061248">doi.org/10.21436/inbor.14061248</a></p></li>
<li><p>Westra T., Oosterlynck P., Govaere L., Leyssen A., Denys L., Packet J., Scheers K., Vanderhaeghe F. and Vanden Borre J. (2022). Monitoring scheme for biotic habitat quality of Natura 2000 habitat types in Flanders, Belgium. Revision of the monitoring design. <em>Reports of the Research Institute for Nature and Forest</em> 2022 (25). Research Institute for Nature and Forest, Brussels. DOI: <a href="doi.org/10.21436/inbor.85829488">doi.org/10.21436/inbor.85829488</a></p></li>
<li><p>Westra T., Oosterlynck P., Van Calster H., Paelinckx D., Denys L., Leyssen A., Packet J., Onkelinx T., Louette G, Waterinckx M en Quataert P (2014). Monitoring Natura 2000 - habitats: meetnet habitatkwaliteit. <em>Rapporten van het Instituut voor Natuur- en Bosonderzoek</em> 2014 (1414229). Instituut voor Natuur- en Bosonderzoek, Brussel.</p></li>
</ul>

</div>
<div id="appendix-bijlagen-.unnumbered-sec-bijlage" class="section level1 hasAnchor" number="12">
<h1><span class="header-section-number">12</span> (APPENDIX) Bijlagen {.unnumbered} {#sec: bijlage}<a href="#appendix-bijlagen-.unnumbered-sec-bijlage" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="bijlage-1-determinatiewerken-sec-bijlage1" class="section level2 hasAnchor" number="12.1">
<h2><span class="header-section-number">12.1</span> Bijlage 1: Determinatiewerken {#sec: bijlage1}<a href="#bijlage-1-determinatiewerken-sec-bijlage1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="algemene-floras" class="section level3 hasAnchor" number="12.1.1">
<h3><span class="header-section-number">12.1.1</span> Algemene flora’s<a href="#algemene-floras" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><p>Duistermaat L. (2020) Heukels’ Flora van Nederland. (24ste editie) Naturalis/Noordhoff ISBN 978-90-01-58956-1</p></li>
<li><p>Eggelte H. (2000) Veldgids Nederlandse Flora. KNNV. ISBN 90 5011 135 1.</p></li>
<li><p>Verloove, Filip &amp; Van Rossum, Fabienne. (2023). Flora van België, het Groothertogdom Luxemburg, Noord-Frankrijk en de aangrenzende gebieden (Pteridofyten en Spermatofyten) (fourth Dutch edition, 2023). Agentschap Plantentuin Meise.</p></li>
<li><p>Rich T.C.G. &amp; Jermy A.C. (1998) Plant Crib. Botanic Society of British Isles. ISBN 0 901158 28 3.</p></li>
<li><p>Rothmaler, W. (1994) Exkursionsflora von Deutschland, Gefässpflanzen: Atlasband 3. Gustav Fischer. ISBN 3-334-60829-8.</p></li>
<li><p>Schou J.C. , Moeslund B., van de Weyer K. , Lansdown R.V., Wiegleb G., Holm P., Baastrup-Spohr L. &amp; K. Sand-Jensen (2023) Aquatic Plants of Northern and Central Europe including Britain and Ireland. WILDGuides ISBN 9780691251011</p></li>
</ul>
</div>
<div id="geïllustreerde-floras" class="section level3 hasAnchor" number="12.1.2">
<h3><span class="header-section-number">12.1.2</span> Geïllustreerde flora’s<a href="#ge%C3%AFllustreerde-floras" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><p>Blaymey M., Grey-Wilson C. (1989) Geïllustreerde Flora . Thieme. ISBN 90 5210 059 4.</p></li>
<li><p>Weeda &amp; Westra (1994) De Nederlansde oecologische flora 1-5. KNNV. ISBN 90 5011 129 7.</p></li>
</ul>
</div>
<div id="atlas" class="section level3 hasAnchor" number="12.1.3">
<h3><span class="header-section-number">12.1.3</span> Atlas<a href="#atlas" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li>Van Landuyt W. et al. (2006) Atlas van de Flora van Vlaanderen en het Brusselse Gewest. Nationale plantentuin van België. ISBN90 726 1968 4.</li>
</ul>
</div>
<div id="herkenning-van-water--enof-oeverplanten" class="section level3 hasAnchor" number="12.1.4">
<h3><span class="header-section-number">12.1.4</span> Herkenning van water- en/of oeverplanten<a href="#herkenning-van-water--enof-oeverplanten" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><p>Haslam et al. (1987) British Water Plants. FSC Publications. ISBN 1 85153 107 3.</p></li>
<li><p>Hoogers et al. (1983) Herkenning van de voornaamste water- en oeverplanten in vegetatieve toestand. Pudoc, Wageningen. ISBN 90 220 0833 9.</p></li>
<li><p>Meriaux et al. (s.d.) Guide pratique de détermination des plantes aquatiques à l’état vegetatif du bassin Artois-Picardie. Agence de l’eau.</p></li>
<li><p>Orton et al. (2000) zoekkaart algemeen voorkomende waterplanten. AMINAL.</p></li>
<li><p>Preston C.D. (2001) Aquatic plants in Britain and Ireland. BSBI. ISBN 0 946589 69 0.</p></li>
<li><p>Roelf Pot (2002) Veldgids Water- en oeverplanten. KNNV. ISBN90 5011 151 3.</p></li>
<li><p>van de Wijer, Schmidt, Kreimeier, Wassong (2018) Fachbeiträge des LfU Heft Nr. 119. Bestimmungsschlüssel für die aquatischen Makrophyten (Gefässpflanzen, Armleuchteralgen und Moose) in Deutschland. Ministerium für Ländliche Entwicklung, Umwelt und Landwirtschaft des Landes Brandenburg.</p></li>
</ul>
</div>
<div id="gerichte-determinatiewerken" class="section level3 hasAnchor" number="12.1.5">
<h3><span class="header-section-number">12.1.5</span> Gerichte determinatiewerken<a href="#gerichte-determinatiewerken" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><p>Aichele &amp; Schwegler (2002) Grassengids. Tirion. ISBN 90-5210-467-0.</p></li>
<li><p>Bruinsma et al. (2018) Determinatietabel van kranswieren van de Benelux. Stichting Jeugdbondsuitgeverij. ISBN 978 90 5107 060 6.</p></li>
<li><p>Fitter et al. (1984) Grasses, sedges, rushes and ferns of Britain and Northern Europe. Collings. ISBN 0 670 80688 9.</p></li>
<li><p>Hermans et al. (1988) Zeggen van Limburg. KNNV. ISBN 90 5011 020 7.</p></li>
<li><p>Hubbard (1992) Grasses. Penguin. ISBN 0-14-013227-9.</p></li>
<li><p>Krause W. (1997) Susswasserflora van Mitteleuropa, 18 Charales (Charophyceae). Gustav Fischer. ISBN 3-437-25056-6.</p></li>
<li><p>Lansdown, R.V. (2008) Water Starworts: Callitriche of Europe. BSBI. ISBN 978 09 011 583 69.</p></li>
<li><p>Maier E.X., Bruinsma J. et al. (1998) Handboek Kranswieren. Charaboek Hilversum.</p></li>
<li><p>Moore (2005) Charophytes of Great-Britain and Ireland. BSBI. ISBN090115816X.</p></li>
<li><p>Muller et al. (2006) Plantes invasives en France . Museum Histoire Naturelle. ISBN 2856535704.</p></li>
<li><p>Philips et al. (1980) Grassen, varens, mossen en korstmossen. Centraal Boekhuis. ISBN 90-274-4579-6.</p></li>
<li><p>Preston C.D. (1995) Pondweeds of Great Britain and Ireland. BSBI. ISBN 0 901158 24 0.</p></li>
<li><p>Schotsman D.H. (1967) Les Callitriches. Lechevalier.</p></li>
<li><p>Urbaniak J., Gabka M. (2014) Polish charophytes. An illustrated guide to identification.. Wydawnictwo Uniwersytetu Przyrodniczego we Wrocławiu. ISBN 978-83-7717-166-0.</p></li>
<li><p>van der Ploeg (1990) De Nederlandse breedbladige fonteinkruiden. KNNV. ISBN 90 5011 036 3.</p></li>
<li><p>van Wijk (1986) De smalbladige fonteinkruidsoorten in Nederland, herkenning en oecologie. KNNV.</p></li>
<li><p>Schubert H., Blindow I., Nat E., Korsch H., Gregor T., Denys L., Stewart N., van de Weyer K., Romanov R., Casanova M.T. (2024). Charophytes of Europe. ISBN : 978-3-031-31897-9.</p></li>
</ul>
</div>
<div id="artikels" class="section level3 hasAnchor" number="12.1.6">
<h3><span class="header-section-number">12.1.6</span> Artikels<a href="#artikels" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><p>Denys L., Packet J., Van Landuyt W. (2004) Neofyten in het Vlaamse water: signalement van vaste waarden en rijzende sterren. Natuur.focus.</p></li>
<li><p>Van Landuyt W. (2007) Herkenning van de vier in België voorkomende drijvende Lemna-soorten. Dumortiera.</p></li>
</ul>
</div>
</div>
<div id="bijlage-2-veldformulier-habitattype-2190_a-sec-bijlage2" class="section level2 hasAnchor" number="12.2">
<h2><span class="header-section-number">12.2</span> Bijlage 2: Veldformulier habitattype 2190_a {#sec: bijlage2}<a href="#bijlage-2-veldformulier-habitattype-2190_a-sec-bijlage2" class="anchor-section" aria-label="Anchor link to header"></a></h2>
</div>
<div id="bijlage-3-veldformulier-habitattype-3110-sec-bijlage3" class="section level2 hasAnchor" number="12.3">
<h2><span class="header-section-number">12.3</span> Bijlage 3: Veldformulier habitattype 3110 {#sec: bijlage3}<a href="#bijlage-3-veldformulier-habitattype-3110-sec-bijlage3" class="anchor-section" aria-label="Anchor link to header"></a></h2>
</div>
<div id="bijlage-4-veldformulier-habitattype-3130_aom-sec-bijlage4" class="section level2 hasAnchor" number="12.4">
<h2><span class="header-section-number">12.4</span> Bijlage 4: Veldformulier habitattype 3130_aom {#sec: bijlage4}<a href="#bijlage-4-veldformulier-habitattype-3130_aom-sec-bijlage4" class="anchor-section" aria-label="Anchor link to header"></a></h2>
</div>
<div id="bijlage-5-veldformulier-habitattype-3130_na-sec-bijlage5" class="section level2 hasAnchor" number="12.5">
<h2><span class="header-section-number">12.5</span> Bijlage 5: Veldformulier habitattype 3130_na {#sec: bijlage5}<a href="#bijlage-5-veldformulier-habitattype-3130_na-sec-bijlage5" class="anchor-section" aria-label="Anchor link to header"></a></h2>
</div>
<div id="bijlage-6-veldformulier-habitattype-3140-sec-bijlage6" class="section level2 hasAnchor" number="12.6">
<h2><span class="header-section-number">12.6</span> Bijlage 6: Veldformulier habitattype 3140 {#sec: bijlage6}<a href="#bijlage-6-veldformulier-habitattype-3140-sec-bijlage6" class="anchor-section" aria-label="Anchor link to header"></a></h2>
</div>
<div id="bijlage-7-veldformulier-habitattype-3150-sec-bijlage7" class="section level2 hasAnchor" number="12.7">
<h2><span class="header-section-number">12.7</span> Bijlage 7: Veldformulier habitattype 3150 {#sec: bijlage7}<a href="#bijlage-7-veldformulier-habitattype-3150-sec-bijlage7" class="anchor-section" aria-label="Anchor link to header"></a></h2>
</div>
<div id="bijlage-8-veldformulier-habitattype-3160-sec-bijlage8" class="section level2 hasAnchor" number="12.8">
<h2><span class="header-section-number">12.8</span> Bijlage 8: Veldformulier habitattype 3160 {#sec: bijlage8}<a href="#bijlage-8-veldformulier-habitattype-3160-sec-bijlage8" class="anchor-section" aria-label="Anchor link to header"></a></h2>


</div>
</div>

<p>&nbsp;</p>
<p><a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons-Licentie" style="border-width:0" src="css/img/cc-by.png" class = "cc"/></a>
            </section>
        </div>
      </div>
    </div>


  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": ["sfp_402_nl_lsvi_stil_water.pdf"],
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>


</body>

</html>
